if(typeof Math.imul == "undefined" || (Math.imul(0xffffffff,5) == 0)) {
    Math.imul = function (a, b) {
        var ah  = (a >>> 16) & 0xffff;
        var al = a & 0xffff;
        var bh  = (b >>> 16) & 0xffff;
        var bl = b & 0xffff;
        // the shift by 0 fixes the sign on the high part
        // the final |0 converts the unsigned value into a signed value
        return ((al * bl) + (((ah * bl + al * bh) << 16) >>> 0)|0);
    }
}


var f;
function p(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}var ba="closure_uid_"+(1E9*Math.random()>>>0),da=0;function ea(a,b){for(var c in a)b.call(void 0,a[c],c,a)};function ga(a,b){null!=a&&this.append.apply(this,arguments)}f=ga.prototype;f.Ja="";f.set=function(a){this.Ja=""+a};f.append=function(a,b,c){this.Ja+=a;if(null!=b)for(var d=1;d<arguments.length;d++)this.Ja+=arguments[d];return this};f.clear=function(){this.Ja=""};f.toString=function(){return this.Ja};function ja(a,b){a.sort(b||ka)}function la(a,b){for(var c=0;c<a.length;c++)a[c]={index:c,value:a[c]};var d=b||ka;ja(a,function(a,b){return d(a.value,b.value)||a.index-b.index});for(c=0;c<a.length;c++)a[c]=a[c].value}function ka(a,b){return a>b?1:a<b?-1:0};var ma;if("undefined"===typeof oa)var oa=function(){throw Error("No *print-fn* fn set for evaluation environment");};if("undefined"===typeof pa)var pa=function(){throw Error("No *print-err-fn* fn set for evaluation environment");};var ra=null;if("undefined"===typeof sa)var sa=null;function ta(){return new ua(null,5,[wa,!0,xa,!0,za,!1,Aa,!1,Ca,null],null)}function u(a){return null!=a&&!1!==a}function Da(a){return a instanceof Array}function Ea(a){return null==a?!0:!1===a?!0:!1}
function v(a,b){return a[p(null==b?null:b)]?!0:a._?!0:!1}function y(a,b){var c=null==b?null:b.constructor,c=u(u(c)?c.sb:c)?c.eb:p(b);return Error(["No protocol method ",a," defined for type ",c,": ",b].join(""))}function Ga(a){var b=a.eb;return u(b)?b:""+B(a)}var Ha="undefined"!==typeof Symbol&&"function"===p(Symbol)?Symbol.iterator:"@@iterator";function Ia(a){for(var b=a.length,c=Array(b),d=0;;)if(d<b)c[d]=a[d],d+=1;else break;return c}
var Ja={},Ka=function Ka(b){if(null!=b&&null!=b.X)return b.X(b);var c=Ka[p(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=Ka._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("ICounted.-count",b);},La=function La(b,c){if(null!=b&&null!=b.M)return b.M(b,c);var d=La[p(null==b?null:b)];if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);d=La._;if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);throw y("ICollection.-conj",b);},Ma={},C=function C(){for(var b=[],c=arguments.length,d=0;;)if(d<
c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 2:return C.a(arguments[0],arguments[1]);case 3:return C.g(arguments[0],arguments[1],arguments[2]);default:throw Error([B("Invalid arity: "),B(b.length)].join(""));}};C.a=function(a,b){if(null!=a&&null!=a.N)return a.N(a,b);var c=C[p(null==a?null:a)];if(null!=c)return c.a?c.a(a,b):c.call(null,a,b);c=C._;if(null!=c)return c.a?c.a(a,b):c.call(null,a,b);throw y("IIndexed.-nth",a);};
C.g=function(a,b,c){if(null!=a&&null!=a.da)return a.da(a,b,c);var d=C[p(null==a?null:a)];if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);d=C._;if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);throw y("IIndexed.-nth",a);};C.R=3;
var E=function E(b){if(null!=b&&null!=b.V)return b.V(b);var c=E[p(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=E._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("ISeq.-first",b);},G=function G(b){if(null!=b&&null!=b.aa)return b.aa(b);var c=G[p(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=G._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("ISeq.-rest",b);},Na={},Pa={},Qa=function Qa(){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=
1;else break;switch(b.length){case 2:return Qa.a(arguments[0],arguments[1]);case 3:return Qa.g(arguments[0],arguments[1],arguments[2]);default:throw Error([B("Invalid arity: "),B(b.length)].join(""));}};Qa.a=function(a,b){if(null!=a&&null!=a.S)return a.S(a,b);var c=Qa[p(null==a?null:a)];if(null!=c)return c.a?c.a(a,b):c.call(null,a,b);c=Qa._;if(null!=c)return c.a?c.a(a,b):c.call(null,a,b);throw y("ILookup.-lookup",a);};
Qa.g=function(a,b,c){if(null!=a&&null!=a.G)return a.G(a,b,c);var d=Qa[p(null==a?null:a)];if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);d=Qa._;if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);throw y("ILookup.-lookup",a);};Qa.R=3;
var Ra=function Ra(b,c,d){if(null!=b&&null!=b.Ra)return b.Ra(b,c,d);var e=Ra[p(null==b?null:b)];if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);e=Ra._;if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);throw y("IAssociative.-assoc",b);},Ta={},Ua={},Va=function Va(b){if(null!=b&&null!=b.kb)return b.kb();var c=Va[p(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=Va._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("IMapEntry.-key",b);},Wa=function Wa(b){if(null!=b&&null!=b.lb)return b.lb();
var c=Wa[p(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=Wa._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("IMapEntry.-val",b);},Xa=function Xa(b){if(null!=b&&null!=b.Va)return b.Va(b);var c=Xa[p(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=Xa._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("IStack.-peek",b);},Ya=function Ya(b){if(null!=b&&null!=b.Wa)return b.Wa(b);var c=Ya[p(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=Ya._;if(null!=
c)return c.c?c.c(b):c.call(null,b);throw y("IStack.-pop",b);},$a={},ab=function ab(b,c,d){if(null!=b&&null!=b.mb)return b.mb(b,c,d);var e=ab[p(null==b?null:b)];if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);e=ab._;if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);throw y("IVector.-assoc-n",b);},bb={},cb=function cb(b){if(null!=b&&null!=b.H)return b.H(b);var c=cb[p(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=cb._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("IMeta.-meta",
b);},db=function db(b,c){if(null!=b&&null!=b.K)return b.K(b,c);var d=db[p(null==b?null:b)];if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);d=db._;if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);throw y("IWithMeta.-with-meta",b);},eb={},fb=function fb(){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 2:return fb.a(arguments[0],arguments[1]);case 3:return fb.g(arguments[0],arguments[1],arguments[2]);default:throw Error([B("Invalid arity: "),B(b.length)].join(""));
}};fb.a=function(a,b){if(null!=a&&null!=a.T)return a.T(a,b);var c=fb[p(null==a?null:a)];if(null!=c)return c.a?c.a(a,b):c.call(null,a,b);c=fb._;if(null!=c)return c.a?c.a(a,b):c.call(null,a,b);throw y("IReduce.-reduce",a);};fb.g=function(a,b,c){if(null!=a&&null!=a.U)return a.U(a,b,c);var d=fb[p(null==a?null:a)];if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);d=fb._;if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);throw y("IReduce.-reduce",a);};fb.R=3;
var gb=function gb(b,c){if(null!=b&&null!=b.o)return b.o(b,c);var d=gb[p(null==b?null:b)];if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);d=gb._;if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);throw y("IEquiv.-equiv",b);},hb=function hb(b){if(null!=b&&null!=b.F)return b.F(b);var c=hb[p(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=hb._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("IHash.-hash",b);},ib={},lb=function lb(b){if(null!=b&&null!=b.P)return b.P(b);var c=lb[p(null==
b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=lb._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("ISeqable.-seq",b);},mb={},nb={},H=function H(b,c){if(null!=b&&null!=b.rb)return b.rb(0,c);var d=H[p(null==b?null:b)];if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);d=H._;if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);throw y("IWriter.-write",b);},ob=function ob(b,c,d){if(null!=b&&null!=b.D)return b.D(b,c,d);var e=ob[p(null==b?null:b)];if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,
c,d);e=ob._;if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);throw y("IPrintWithWriter.-pr-writer",b);},pb=function pb(b){if(null!=b&&null!=b.Ta)return b.Ta(b);var c=pb[p(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=pb._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("IEditableCollection.-as-transient",b);},qb=function qb(b,c){if(null!=b&&null!=b.bb)return b.bb(b,c);var d=qb[p(null==b?null:b)];if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);d=qb._;if(null!=d)return d.a?d.a(b,
c):d.call(null,b,c);throw y("ITransientCollection.-conj!",b);},rb=function rb(b){if(null!=b&&null!=b.cb)return b.cb(b);var c=rb[p(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=rb._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("ITransientCollection.-persistent!",b);},sb=function sb(b,c,d){if(null!=b&&null!=b.Xa)return b.Xa(b,c,d);var e=sb[p(null==b?null:b)];if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);e=sb._;if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);throw y("ITransientAssociative.-assoc!",
b);},tb=function tb(b,c,d){if(null!=b&&null!=b.qb)return b.qb(0,c,d);var e=tb[p(null==b?null:b)];if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);e=tb._;if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);throw y("ITransientVector.-assoc-n!",b);},ub={},vb=function vb(b,c){if(null!=b&&null!=b.Oa)return b.Oa(b,c);var d=vb[p(null==b?null:b)];if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);d=vb._;if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);throw y("IComparable.-compare",b);},wb=function wb(b){if(null!=
b&&null!=b.ob)return b.ob();var c=wb[p(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=wb._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("IChunk.-drop-first",b);},xb=function xb(b){if(null!=b&&null!=b.ib)return b.ib(b);var c=xb[p(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=xb._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("IChunkedSeq.-chunked-first",b);},I=function I(b){if(null!=b&&null!=b.jb)return b.jb(b);var c=I[p(null==b?null:b)];if(null!=c)return c.c?
c.c(b):c.call(null,b);c=I._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("IChunkedSeq.-chunked-rest",b);},yb=function yb(b){if(null!=b&&null!=b.hb)return b.hb(b);var c=yb[p(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=yb._;if(null!=c)return c.c?c.c(b):c.call(null,b);throw y("IChunkedNext.-chunked-next",b);},Ab=function Ab(b){if(null!=b&&null!=b.Fa)return b.Fa(b);var c=Ab[p(null==b?null:b)];if(null!=c)return c.c?c.c(b):c.call(null,b);c=Ab._;if(null!=c)return c.c?c.c(b):c.call(null,
b);throw y("IIterable.-iterator",b);};function Bb(a){this.Gb=a;this.j=1073741824;this.u=0}Bb.prototype.rb=function(a,b){return this.Gb.append(b)};function Cb(a){var b=new ga;a.D(null,new Bb(b),ta());return""+B(b)}var Db="undefined"!==typeof Math.imul&&0!==Math.imul(4294967295,5)?function(a,b){return Math.imul(a,b)}:function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0};function Eb(a){a=Db(a|0,-862048943);return Db(a<<15|a>>>-15,461845907)}
function Fb(a,b){var c=(a|0)^(b|0);return Db(c<<13|c>>>-13,5)+-430675100|0}function Gb(a,b){var c=(a|0)^b,c=Db(c^c>>>16,-2048144789),c=Db(c^c>>>13,-1028477387);return c^c>>>16}function Hb(a){var b;a:{b=1;for(var c=0;;)if(b<a.length){var d=b+2,c=Fb(c,Eb(a.charCodeAt(b-1)|a.charCodeAt(b)<<16));b=d}else{b=c;break a}}b=1===(a.length&1)?b^Eb(a.charCodeAt(a.length-1)):b;return Gb(b,Db(2,a.length))}var Ib={},Jb=0;
function Kb(a){255<Jb&&(Ib={},Jb=0);var b=Ib[a];if("number"!==typeof b){a:if(null!=a)if(b=a.length,0<b)for(var c=0,d=0;;)if(c<b)var e=c+1,d=Db(31,d)+a.charCodeAt(c),c=e;else{b=d;break a}else b=0;else b=0;Ib[a]=b;Jb+=1}return a=b}function Lb(a){null!=a&&(a.j&4194304||a.Jb)?a=a.F(null):"number"===typeof a?a=Math.floor(a)%2147483647:!0===a?a=1:!1===a?a=0:"string"===typeof a?(a=Kb(a),0!==a&&(a=Eb(a),a=Fb(0,a),a=Gb(a,4))):a=a instanceof Date?a.valueOf():null==a?0:hb(a);return a}
function Mb(a,b){return a^b+2654435769+(a<<6)+(a>>2)}function Ob(a,b){if(a.oa===b.oa)return 0;var c=Ea(a.Z);if(u(c?b.Z:c))return-1;if(u(a.Z)){if(Ea(b.Z))return 1;c=ka(a.Z,b.Z);return 0===c?ka(a.name,b.name):c}return ka(a.name,b.name)}function Pb(a,b,c,d,e){this.Z=a;this.name=b;this.oa=c;this.Na=d;this.ga=e;this.j=2154168321;this.u=4096}f=Pb.prototype;f.toString=function(){return this.oa};f.equiv=function(a){return this.o(null,a)};f.o=function(a,b){return b instanceof Pb?this.oa===b.oa:!1};
f.call=function(){function a(a,b,c){return Qb?Qb(b,this,c):Rb.call(null,b,this,c)}function b(a,b){return Sb?Sb(b,this):Rb.call(null,b,this)}var c=null,c=function(c,e,g){switch(arguments.length){case 2:return b.call(this,0,e);case 3:return a.call(this,0,e,g)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.g=a;return c}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ia(b)))};f.c=function(a){return Sb?Sb(a,this):Rb.call(null,a,this)};
f.a=function(a,b){return Qb?Qb(a,this,b):Rb.call(null,a,this,b)};f.H=function(){return this.ga};f.K=function(a,b){return new Pb(this.Z,this.name,this.oa,this.Na,b)};f.F=function(){var a=this.Na;return null!=a?a:this.Na=a=Mb(Hb(this.name),Kb(this.Z))};f.D=function(a,b){return H(b,this.oa)};
function J(a){if(null==a)return null;if(null!=a&&(a.j&8388608||a.Cb))return a.P(null);if(Da(a)||"string"===typeof a)return 0===a.length?null:new K(a,0);if(v(ib,a))return lb(a);throw Error([B(a),B(" is not ISeqable")].join(""));}function M(a){if(null==a)return null;if(null!=a&&(a.j&64||a.Ua))return a.V(null);a=J(a);return null==a?null:E(a)}function N(a){return null!=a?null!=a&&(a.j&64||a.Ua)?a.aa(null):(a=J(a))?G(a):Tb:Tb}
function O(a){return null==a?null:null!=a&&(a.j&128||a.ab)?a.$(null):J(N(a))}var P=function P(){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 1:return P.c(arguments[0]);case 2:return P.a(arguments[0],arguments[1]);default:return P.w(arguments[0],arguments[1],new K(b.slice(2),0))}};P.c=function(){return!0};P.a=function(a,b){return null==a?null==b:a===b||gb(a,b)};
P.w=function(a,b,c){for(;;)if(P.a(a,b))if(O(c))a=b,b=M(c),c=O(c);else return P.a(b,M(c));else return!1};P.I=function(a){var b=M(a),c=O(a);a=M(c);c=O(c);return P.w(b,a,c)};P.R=2;function Ub(a){this.v=a}Ub.prototype.next=function(){if(null!=this.v){var a=M(this.v);this.v=O(this.v);return{value:a,done:!1}}return{value:null,done:!0}};function Q(a){return new Ub(J(a))}function Vb(a,b){var c=Eb(a),c=Fb(0,c);return Gb(c,b)}
function Wb(a){var b=0,c=1;for(a=J(a);;)if(null!=a)b+=1,c=Db(31,c)+Lb(M(a))|0,a=O(a);else return Vb(c,b)}var Xb=Vb(1,0);function Yb(a){var b=0,c=0;for(a=J(a);;)if(null!=a)b+=1,c=c+Lb(M(a))|0,a=O(a);else return Vb(c,b)}var Zb=Vb(0,0);Ja["null"]=!0;Ka["null"]=function(){return 0};Date.prototype.o=function(a,b){return b instanceof Date&&this.valueOf()===b.valueOf()};Date.prototype.Sa=!0;
Date.prototype.Oa=function(a,b){if(b instanceof Date)return ka(this.valueOf(),b.valueOf());throw Error([B("Cannot compare "),B(this),B(" to "),B(b)].join(""));};gb.number=function(a,b){return a===b};bb["function"]=!0;cb["function"]=function(){return null};hb._=function(a){return a[ba]||(a[ba]=++da)};function $b(a,b){var c=Ka(a);if(0===c)return b.C?b.C():b.call(null);for(var d=C.a(a,0),e=1;;)if(e<c)var g=C.a(a,e),d=b.a?b.a(d,g):b.call(null,d,g),e=e+1;else return d}
function ac(a,b,c){var d=Ka(a),e=c;for(c=0;;)if(c<d){var g=C.a(a,c),e=b.a?b.a(e,g):b.call(null,e,g);c+=1}else return e}function bc(a,b){var c=a.length;if(0===a.length)return b.C?b.C():b.call(null);for(var d=a[0],e=1;;)if(e<c)var g=a[e],d=b.a?b.a(d,g):b.call(null,d,g),e=e+1;else return d}function cc(a,b,c){var d=a.length,e=c;for(c=0;;)if(c<d){var g=a[c],e=b.a?b.a(e,g):b.call(null,e,g);c+=1}else return e}
function dc(a,b,c,d){for(var e=a.length;;)if(d<e){var g=a[d];c=b.a?b.a(c,g):b.call(null,c,g);d+=1}else return c}function ec(a){return null!=a?a.j&2||a.ub?!0:a.j?!1:v(Ja,a):v(Ja,a)}function fc(a){return null!=a?a.j&16||a.pb?!0:a.j?!1:v(Ma,a):v(Ma,a)}function gc(a,b){this.b=a;this.i=b}gc.prototype.ha=function(){return this.i<this.b.length};gc.prototype.next=function(){var a=this.b[this.i];this.i+=1;return a};function K(a,b){this.b=a;this.i=b;this.j=166199550;this.u=8192}f=K.prototype;f.toString=function(){return Cb(this)};
f.equiv=function(a){return this.o(null,a)};f.N=function(a,b){var c=b+this.i;return c<this.b.length?this.b[c]:null};f.da=function(a,b,c){a=b+this.i;return a<this.b.length?this.b[a]:c};f.Fa=function(){return new gc(this.b,this.i)};f.$=function(){return this.i+1<this.b.length?new K(this.b,this.i+1):null};f.X=function(){var a=this.b.length-this.i;return 0>a?0:a};f.F=function(){return Wb(this)};f.o=function(a,b){return ic.a?ic.a(this,b):ic.call(null,this,b)};
f.T=function(a,b){return dc(this.b,b,this.b[this.i],this.i+1)};f.U=function(a,b,c){return dc(this.b,b,c,this.i)};f.V=function(){return this.b[this.i]};f.aa=function(){return this.i+1<this.b.length?new K(this.b,this.i+1):Tb};f.P=function(){return this.i<this.b.length?this:null};f.M=function(a,b){return R.a?R.a(b,this):R.call(null,b,this)};K.prototype[Ha]=function(){return Q(this)};function jc(a,b){return b<a.length?new K(a,b):null}
function kc(){for(var a=[],b=arguments.length,c=0;;)if(c<b)a.push(arguments[c]),c+=1;else break;switch(a.length){case 1:return jc(arguments[0],0);case 2:return jc(arguments[0],arguments[1]);default:throw Error([B("Invalid arity: "),B(a.length)].join(""));}}function lc(a){return M(O(a))}gb._=function(a,b){return a===b};
var S=function S(){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 0:return S.C();case 1:return S.c(arguments[0]);case 2:return S.a(arguments[0],arguments[1]);default:return S.w(arguments[0],arguments[1],new K(b.slice(2),0))}};S.C=function(){return mc};S.c=function(a){return a};S.a=function(a,b){return null!=a?La(a,b):La(Tb,b)};S.w=function(a,b,c){for(;;)if(u(c))a=S.a(a,b),b=M(c),c=O(c);else return S.a(a,b)};
S.I=function(a){var b=M(a),c=O(a);a=M(c);c=O(c);return S.w(b,a,c)};S.R=2;function T(a){if(null!=a)if(null!=a&&(a.j&2||a.ub))a=a.X(null);else if(Da(a))a=a.length;else if("string"===typeof a)a=a.length;else if(null!=a&&(a.j&8388608||a.Cb))a:{a=J(a);for(var b=0;;){if(ec(a)){a=b+Ka(a);break a}a=O(a);b+=1}}else a=Ka(a);else a=0;return a}function nc(a,b){for(var c=null;;){if(null==a)return c;if(0===b)return J(a)?M(a):c;if(fc(a))return C.g(a,b,c);if(J(a)){var d=O(a),e=b-1;a=d;b=e}else return c}}
function oc(a,b){if("number"!==typeof b)throw Error("index argument to nth must be a number");if(null==a)return a;if(null!=a&&(a.j&16||a.pb))return a.N(null,b);if(Da(a))return b<a.length?a[b]:null;if("string"===typeof a)return b<a.length?a.charAt(b):null;if(null!=a&&(a.j&64||a.Ua)){var c;a:{c=a;for(var d=b;;){if(null==c)throw Error("Index out of bounds");if(0===d){if(J(c)){c=M(c);break a}throw Error("Index out of bounds");}if(fc(c)){c=C.a(c,d);break a}if(J(c))c=O(c),--d;else throw Error("Index out of bounds");
}}return c}if(v(Ma,a))return C.a(a,b);throw Error([B("nth not supported on this type "),B(Ga(null==a?null:a.constructor))].join(""));}
function U(a,b){if("number"!==typeof b)throw Error("index argument to nth must be a number.");if(null==a)return null;if(null!=a&&(a.j&16||a.pb))return a.da(null,b,null);if(Da(a))return b<a.length?a[b]:null;if("string"===typeof a)return b<a.length?a.charAt(b):null;if(null!=a&&(a.j&64||a.Ua))return nc(a,b);if(v(Ma,a))return C.a(a,b);throw Error([B("nth not supported on this type "),B(Ga(null==a?null:a.constructor))].join(""));}
function Rb(){for(var a=[],b=arguments.length,c=0;;)if(c<b)a.push(arguments[c]),c+=1;else break;switch(a.length){case 2:return Sb(arguments[0],arguments[1]);case 3:return Qb(arguments[0],arguments[1],arguments[2]);default:throw Error([B("Invalid arity: "),B(a.length)].join(""));}}function Sb(a,b){return null==a?null:null!=a&&(a.j&256||a.wb)?a.S(null,b):Da(a)?b<a.length?a[b|0]:null:"string"===typeof a?b<a.length?a[b|0]:null:v(Pa,a)?Qa.a(a,b):null}
function Qb(a,b,c){return null!=a?null!=a&&(a.j&256||a.wb)?a.G(null,b,c):Da(a)?b<a.length?a[b]:c:"string"===typeof a?b<a.length?a[b]:c:v(Pa,a)?Qa.g(a,b,c):c:c}var pc=function pc(){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 3:return pc.g(arguments[0],arguments[1],arguments[2]);default:return pc.w(arguments[0],arguments[1],arguments[2],new K(b.slice(3),0))}};
pc.g=function(a,b,c){if(null!=a)a=Ra(a,b,c);else a:{a=[b];c=[c];b=a.length;var d=0,e;for(e=pb(qc);;)if(d<b){var g=d+1;e=e.Xa(null,a[d],c[d]);d=g}else{a=rb(e);break a}}return a};pc.w=function(a,b,c,d){for(;;)if(a=pc.g(a,b,c),u(d))b=M(d),c=lc(d),d=O(O(d));else return a};pc.I=function(a){var b=M(a),c=O(a);a=M(c);var d=O(c),c=M(d),d=O(d);return pc.w(b,a,c,d)};pc.R=3;function rc(a,b){this.f=a;this.l=b;this.j=393217;this.u=0}f=rc.prototype;f.H=function(){return this.l};
f.K=function(a,b){return new rc(this.f,b)};
f.call=function(){function a(a,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,F,D,L,A,ia){a=this;return sc.$a?sc.$a(a.f,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,F,D,L,A,ia):sc.call(null,a.f,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,F,D,L,A,ia)}function b(a,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,F,D,L,A){a=this;return a.f.Aa?a.f.Aa(b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,F,D,L,A):a.f.call(null,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,F,D,L,A)}function c(a,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,F,D,L){a=this;return a.f.za?a.f.za(b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,F,
D,L):a.f.call(null,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,F,D,L)}function d(a,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,F,D){a=this;return a.f.ya?a.f.ya(b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,F,D):a.f.call(null,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,F,D)}function e(a,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,F){a=this;return a.f.xa?a.f.xa(b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,F):a.f.call(null,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,F)}function g(a,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z){a=this;return a.f.wa?a.f.wa(b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z):a.f.call(null,
b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z)}function h(a,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x){a=this;return a.f.va?a.f.va(b,c,d,e,g,h,k,l,m,n,q,r,t,w,x):a.f.call(null,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x)}function k(a,b,c,d,e,g,h,k,l,m,n,q,r,t,w){a=this;return a.f.ua?a.f.ua(b,c,d,e,g,h,k,l,m,n,q,r,t,w):a.f.call(null,b,c,d,e,g,h,k,l,m,n,q,r,t,w)}function l(a,b,c,d,e,g,h,k,l,m,n,q,r,t){a=this;return a.f.ta?a.f.ta(b,c,d,e,g,h,k,l,m,n,q,r,t):a.f.call(null,b,c,d,e,g,h,k,l,m,n,q,r,t)}function m(a,b,c,d,e,g,h,k,l,m,n,q,r){a=this;
return a.f.sa?a.f.sa(b,c,d,e,g,h,k,l,m,n,q,r):a.f.call(null,b,c,d,e,g,h,k,l,m,n,q,r)}function n(a,b,c,d,e,g,h,k,l,m,n,q){a=this;return a.f.ra?a.f.ra(b,c,d,e,g,h,k,l,m,n,q):a.f.call(null,b,c,d,e,g,h,k,l,m,n,q)}function q(a,b,c,d,e,g,h,k,l,m,n){a=this;return a.f.qa?a.f.qa(b,c,d,e,g,h,k,l,m,n):a.f.call(null,b,c,d,e,g,h,k,l,m,n)}function r(a,b,c,d,e,g,h,k,l,m){a=this;return a.f.Ea?a.f.Ea(b,c,d,e,g,h,k,l,m):a.f.call(null,b,c,d,e,g,h,k,l,m)}function t(a,b,c,d,e,g,h,k,l){a=this;return a.f.Da?a.f.Da(b,c,
d,e,g,h,k,l):a.f.call(null,b,c,d,e,g,h,k,l)}function w(a,b,c,d,e,g,h,k){a=this;return a.f.Ca?a.f.Ca(b,c,d,e,g,h,k):a.f.call(null,b,c,d,e,g,h,k)}function x(a,b,c,d,e,g,h){a=this;return a.f.Ba?a.f.Ba(b,c,d,e,g,h):a.f.call(null,b,c,d,e,g,h)}function z(a,b,c,d,e,g){a=this;return a.f.Y?a.f.Y(b,c,d,e,g):a.f.call(null,b,c,d,e,g)}function D(a,b,c,d,e){a=this;return a.f.ca?a.f.ca(b,c,d,e):a.f.call(null,b,c,d,e)}function F(a,b,c,d){a=this;return a.f.g?a.f.g(b,c,d):a.f.call(null,b,c,d)}function L(a,b,c){a=this;
return a.f.a?a.f.a(b,c):a.f.call(null,b,c)}function ia(a,b){a=this;return a.f.c?a.f.c(b):a.f.call(null,b)}function kb(a){a=this;return a.f.C?a.f.C():a.f.call(null)}var A=null,A=function(A,aa,ca,fa,ha,na,qa,va,ya,Ba,Fa,Oa,Sa,Za,jb,zb,Nb,hc,Jc,gd,je,af){switch(arguments.length){case 1:return kb.call(this,A);case 2:return ia.call(this,A,aa);case 3:return L.call(this,A,aa,ca);case 4:return F.call(this,A,aa,ca,fa);case 5:return D.call(this,A,aa,ca,fa,ha);case 6:return z.call(this,A,aa,ca,fa,ha,na);case 7:return x.call(this,
A,aa,ca,fa,ha,na,qa);case 8:return w.call(this,A,aa,ca,fa,ha,na,qa,va);case 9:return t.call(this,A,aa,ca,fa,ha,na,qa,va,ya);case 10:return r.call(this,A,aa,ca,fa,ha,na,qa,va,ya,Ba);case 11:return q.call(this,A,aa,ca,fa,ha,na,qa,va,ya,Ba,Fa);case 12:return n.call(this,A,aa,ca,fa,ha,na,qa,va,ya,Ba,Fa,Oa);case 13:return m.call(this,A,aa,ca,fa,ha,na,qa,va,ya,Ba,Fa,Oa,Sa);case 14:return l.call(this,A,aa,ca,fa,ha,na,qa,va,ya,Ba,Fa,Oa,Sa,Za);case 15:return k.call(this,A,aa,ca,fa,ha,na,qa,va,ya,Ba,Fa,Oa,
Sa,Za,jb);case 16:return h.call(this,A,aa,ca,fa,ha,na,qa,va,ya,Ba,Fa,Oa,Sa,Za,jb,zb);case 17:return g.call(this,A,aa,ca,fa,ha,na,qa,va,ya,Ba,Fa,Oa,Sa,Za,jb,zb,Nb);case 18:return e.call(this,A,aa,ca,fa,ha,na,qa,va,ya,Ba,Fa,Oa,Sa,Za,jb,zb,Nb,hc);case 19:return d.call(this,A,aa,ca,fa,ha,na,qa,va,ya,Ba,Fa,Oa,Sa,Za,jb,zb,Nb,hc,Jc);case 20:return c.call(this,A,aa,ca,fa,ha,na,qa,va,ya,Ba,Fa,Oa,Sa,Za,jb,zb,Nb,hc,Jc,gd);case 21:return b.call(this,A,aa,ca,fa,ha,na,qa,va,ya,Ba,Fa,Oa,Sa,Za,jb,zb,Nb,hc,Jc,gd,
je);case 22:return a.call(this,A,aa,ca,fa,ha,na,qa,va,ya,Ba,Fa,Oa,Sa,Za,jb,zb,Nb,hc,Jc,gd,je,af)}throw Error("Invalid arity: "+arguments.length);};A.c=kb;A.a=ia;A.g=L;A.ca=F;A.Y=D;A.Ba=z;A.Ca=x;A.Da=w;A.Ea=t;A.qa=r;A.ra=q;A.sa=n;A.ta=m;A.ua=l;A.va=k;A.wa=h;A.xa=g;A.ya=e;A.za=d;A.Aa=c;A.vb=b;A.$a=a;return A}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ia(b)))};f.C=function(){return this.f.C?this.f.C():this.f.call(null)};
f.c=function(a){return this.f.c?this.f.c(a):this.f.call(null,a)};f.a=function(a,b){return this.f.a?this.f.a(a,b):this.f.call(null,a,b)};f.g=function(a,b,c){return this.f.g?this.f.g(a,b,c):this.f.call(null,a,b,c)};f.ca=function(a,b,c,d){return this.f.ca?this.f.ca(a,b,c,d):this.f.call(null,a,b,c,d)};f.Y=function(a,b,c,d,e){return this.f.Y?this.f.Y(a,b,c,d,e):this.f.call(null,a,b,c,d,e)};f.Ba=function(a,b,c,d,e,g){return this.f.Ba?this.f.Ba(a,b,c,d,e,g):this.f.call(null,a,b,c,d,e,g)};
f.Ca=function(a,b,c,d,e,g,h){return this.f.Ca?this.f.Ca(a,b,c,d,e,g,h):this.f.call(null,a,b,c,d,e,g,h)};f.Da=function(a,b,c,d,e,g,h,k){return this.f.Da?this.f.Da(a,b,c,d,e,g,h,k):this.f.call(null,a,b,c,d,e,g,h,k)};f.Ea=function(a,b,c,d,e,g,h,k,l){return this.f.Ea?this.f.Ea(a,b,c,d,e,g,h,k,l):this.f.call(null,a,b,c,d,e,g,h,k,l)};f.qa=function(a,b,c,d,e,g,h,k,l,m){return this.f.qa?this.f.qa(a,b,c,d,e,g,h,k,l,m):this.f.call(null,a,b,c,d,e,g,h,k,l,m)};
f.ra=function(a,b,c,d,e,g,h,k,l,m,n){return this.f.ra?this.f.ra(a,b,c,d,e,g,h,k,l,m,n):this.f.call(null,a,b,c,d,e,g,h,k,l,m,n)};f.sa=function(a,b,c,d,e,g,h,k,l,m,n,q){return this.f.sa?this.f.sa(a,b,c,d,e,g,h,k,l,m,n,q):this.f.call(null,a,b,c,d,e,g,h,k,l,m,n,q)};f.ta=function(a,b,c,d,e,g,h,k,l,m,n,q,r){return this.f.ta?this.f.ta(a,b,c,d,e,g,h,k,l,m,n,q,r):this.f.call(null,a,b,c,d,e,g,h,k,l,m,n,q,r)};
f.ua=function(a,b,c,d,e,g,h,k,l,m,n,q,r,t){return this.f.ua?this.f.ua(a,b,c,d,e,g,h,k,l,m,n,q,r,t):this.f.call(null,a,b,c,d,e,g,h,k,l,m,n,q,r,t)};f.va=function(a,b,c,d,e,g,h,k,l,m,n,q,r,t,w){return this.f.va?this.f.va(a,b,c,d,e,g,h,k,l,m,n,q,r,t,w):this.f.call(null,a,b,c,d,e,g,h,k,l,m,n,q,r,t,w)};f.wa=function(a,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x){return this.f.wa?this.f.wa(a,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x):this.f.call(null,a,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x)};
f.xa=function(a,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z){return this.f.xa?this.f.xa(a,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z):this.f.call(null,a,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z)};f.ya=function(a,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,D){return this.f.ya?this.f.ya(a,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,D):this.f.call(null,a,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,D)};
f.za=function(a,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,D,F){return this.f.za?this.f.za(a,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,D,F):this.f.call(null,a,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,D,F)};f.Aa=function(a,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,D,F,L){return this.f.Aa?this.f.Aa(a,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,D,F,L):this.f.call(null,a,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,D,F,L)};
f.vb=function(a,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,D,F,L,ia){return sc.$a?sc.$a(this.f,a,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,D,F,L,ia):sc.call(null,this.f,a,b,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,D,F,L,ia)};function tc(a,b){return"function"==p(a)?new rc(a,b):null==a?null:db(a,b)}function uc(a){var b=null!=a;return(b?null!=a?a.j&131072||a.zb||(a.j?0:v(bb,a)):v(bb,a):b)?cb(a):null}function vc(a){return null==a||Ea(J(a))}function wc(a){return null!=a?a.j&16777216||a.Lb?!0:a.j?!1:v(mb,a):v(mb,a)}
function xc(a){return null==a?!1:null!=a?a.j&1024||a.xb?!0:a.j?!1:v(Ta,a):v(Ta,a)}function yc(a){return null!=a?a.j&16384||a.Mb?!0:a.j?!1:v($a,a):v($a,a)}function zc(a){return null!=a?a.u&512||a.Hb?!0:!1:!1}function Ac(a){var b=[];ea(a,function(a,b){return function(a,c){return b.push(c)}}(a,b));return b}function Bc(a,b,c,d,e){for(;0!==e;)c[d]=a[b],d+=1,--e,b+=1}var Cc={};function Dc(a){return null==a?!1:!1===a?!1:!0}
function Ec(a,b){if(a===b)return 0;if(null==a)return-1;if(null==b)return 1;if("number"===typeof a){if("number"===typeof b)return ka(a,b);throw Error([B("Cannot compare "),B(a),B(" to "),B(b)].join(""));}if(null!=a?a.u&2048||a.Sa||(a.u?0:v(ub,a)):v(ub,a))return vb(a,b);if("string"!==typeof a&&!Da(a)&&!0!==a&&!1!==a||(null==a?null:a.constructor)!==(null==b?null:b.constructor))throw Error([B("Cannot compare "),B(a),B(" to "),B(b)].join(""));return ka(a,b)}
function Fc(a,b){var c=T(a),d=T(b);if(c<d)c=-1;else if(c>d)c=1;else if(0===c)c=0;else a:for(d=0;;){var e=Ec(oc(a,d),oc(b,d));if(0===e&&d+1<c)d+=1;else{c=e;break a}}return c}function Gc(a){return P.a(a,Ec)?Ec:function(b,c){var d=a.a?a.a(b,c):a.call(null,b,c);return"number"===typeof d?d:u(d)?-1:u(a.a?a.a(c,b):a.call(null,c,b))?1:0}}function Hc(a,b){if(J(b)){var c=Ic.c?Ic.c(b):Ic.call(null,b),d=Gc(a);la(c,d);return J(c)}return Tb}function Kc(a,b){return Lc(a,b)}
function Lc(a,b){return Hc(function(b,d){return Gc(Ec).call(null,a.c?a.c(b):a.call(null,b),a.c?a.c(d):a.call(null,d))},b)}function Mc(a,b){var c=J(b);if(c){var d=M(c),c=O(c);return Nc?Nc(a,d,c):Oc.call(null,a,d,c)}return a.C?a.C():a.call(null)}function Pc(a,b,c){for(c=J(c);;)if(c){var d=M(c);b=a.a?a.a(b,d):a.call(null,b,d);c=O(c)}else return b}
function Oc(){for(var a=[],b=arguments.length,c=0;;)if(c<b)a.push(arguments[c]),c+=1;else break;switch(a.length){case 2:return Qc(arguments[0],arguments[1]);case 3:return Nc(arguments[0],arguments[1],arguments[2]);default:throw Error([B("Invalid arity: "),B(a.length)].join(""));}}function Qc(a,b){return null!=b&&(b.j&524288||b.Bb)?b.T(null,a):Da(b)?bc(b,a):"string"===typeof b?bc(b,a):v(eb,b)?fb.a(b,a):Mc(a,b)}
function Nc(a,b,c){return null!=c&&(c.j&524288||c.Bb)?c.U(null,a,b):Da(c)?cc(c,a,b):"string"===typeof c?cc(c,a,b):v(eb,c)?fb.g(c,a,b):Pc(a,b,c)}function Rc(a){return a}function Sc(a){a=(a-a%2)/2;return 0<=a?Math.floor(a):Math.ceil(a)}function Tc(a){a-=a>>1&1431655765;a=(a&858993459)+(a>>2&858993459);return 16843009*(a+(a>>4)&252645135)>>24}
var B=function B(){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 0:return B.C();case 1:return B.c(arguments[0]);default:return B.w(arguments[0],new K(b.slice(1),0))}};B.C=function(){return""};B.c=function(a){return null==a?"":""+a};B.w=function(a,b){for(var c=new ga(""+B(a)),d=b;;)if(u(d))c=c.append(""+B(M(d))),d=O(d);else return c.toString()};B.I=function(a){var b=M(a);a=O(a);return B.w(b,a)};B.R=1;
function ic(a,b){var c;if(wc(b))if(ec(a)&&ec(b)&&T(a)!==T(b))c=!1;else a:{c=J(a);for(var d=J(b);;){if(null==c){c=null==d;break a}if(null!=d&&P.a(M(c),M(d)))c=O(c),d=O(d);else{c=!1;break a}}}else c=null;return Dc(c)}function Uc(a,b,c,d,e){this.l=a;this.first=b;this.Ga=c;this.count=d;this.m=e;this.j=65937646;this.u=8192}f=Uc.prototype;f.toString=function(){return Cb(this)};f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.l};f.$=function(){return 1===this.count?null:this.Ga};
f.X=function(){return this.count};f.Va=function(){return this.first};f.Wa=function(){return G(this)};f.F=function(){var a=this.m;return null!=a?a:this.m=a=Wb(this)};f.o=function(a,b){return ic(this,b)};f.T=function(a,b){return Mc(b,this)};f.U=function(a,b,c){return Pc(b,c,this)};f.V=function(){return this.first};f.aa=function(){return 1===this.count?Tb:this.Ga};f.P=function(){return this};f.K=function(a,b){return new Uc(b,this.first,this.Ga,this.count,this.m)};
f.M=function(a,b){return new Uc(this.l,b,this,this.count+1,null)};Uc.prototype[Ha]=function(){return Q(this)};function Vc(a){this.l=a;this.j=65937614;this.u=8192}f=Vc.prototype;f.toString=function(){return Cb(this)};f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.l};f.$=function(){return null};f.X=function(){return 0};f.Va=function(){return null};f.Wa=function(){throw Error("Can't pop empty list");};f.F=function(){return Xb};
f.o=function(a,b){return(null!=b?b.j&33554432||b.Kb||(b.j?0:v(nb,b)):v(nb,b))||wc(b)?null==J(b):!1};f.T=function(a,b){return Mc(b,this)};f.U=function(a,b,c){return Pc(b,c,this)};f.V=function(){return null};f.aa=function(){return Tb};f.P=function(){return null};f.K=function(a,b){return new Vc(b)};f.M=function(a,b){return new Uc(this.l,b,null,1,null)};var Tb=new Vc(null);Vc.prototype[Ha]=function(){return Q(this)};
function Wc(){for(var a=[],b=arguments.length,c=0;;)if(c<b)a.push(arguments[c]),c+=1;else break;a:{b=0<a.length?new K(a.slice(0),0):null;if(b instanceof K&&0===b.i)a=b.b;else b:for(a=[];;)if(null!=b)a.push(b.V(null)),b=b.$(null);else break b;for(var b=a.length,d=Tb;;)if(0<b)c=b-1,d=d.M(null,a[b-1]),b=c;else break a}return d}function Xc(a,b,c,d){this.l=a;this.first=b;this.Ga=c;this.m=d;this.j=65929452;this.u=8192}f=Xc.prototype;f.toString=function(){return Cb(this)};
f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.l};f.$=function(){return null==this.Ga?null:J(this.Ga)};f.F=function(){var a=this.m;return null!=a?a:this.m=a=Wb(this)};f.o=function(a,b){return ic(this,b)};f.T=function(a,b){return Mc(b,this)};f.U=function(a,b,c){return Pc(b,c,this)};f.V=function(){return this.first};f.aa=function(){return null==this.Ga?Tb:this.Ga};f.P=function(){return this};f.K=function(a,b){return new Xc(b,this.first,this.Ga,this.m)};
f.M=function(a,b){return new Xc(null,b,this,this.m)};Xc.prototype[Ha]=function(){return Q(this)};function R(a,b){var c=null==b;return(c?c:null!=b&&(b.j&64||b.Ua))?new Xc(null,a,b,null):new Xc(null,a,J(b),null)}function Yc(a,b){if(a.ma===b.ma)return 0;var c=Ea(a.Z);if(u(c?b.Z:c))return-1;if(u(a.Z)){if(Ea(b.Z))return 1;c=ka(a.Z,b.Z);return 0===c?ka(a.name,b.name):c}return ka(a.name,b.name)}function V(a,b,c,d){this.Z=a;this.name=b;this.ma=c;this.Na=d;this.j=2153775105;this.u=4096}f=V.prototype;
f.toString=function(){return[B(":"),B(this.ma)].join("")};f.equiv=function(a){return this.o(null,a)};f.o=function(a,b){return b instanceof V?this.ma===b.ma:!1};f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return Sb(c,this);case 3:return Qb(c,this,d)}throw Error("Invalid arity: "+arguments.length);};a.a=function(a,c){return Sb(c,this)};a.g=function(a,c,d){return Qb(c,this,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ia(b)))};
f.c=function(a){return Sb(a,this)};f.a=function(a,b){return Qb(a,this,b)};f.F=function(){var a=this.Na;return null!=a?a:this.Na=a=Mb(Hb(this.name),Kb(this.Z))+2654435769|0};f.D=function(a,b){return H(b,[B(":"),B(this.ma)].join(""))};var Zc=function Zc(){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 1:return Zc.c(arguments[0]);case 2:return Zc.a(arguments[0],arguments[1]);default:throw Error([B("Invalid arity: "),B(b.length)].join(""));}};
Zc.c=function(a){if(a instanceof V)return a;if(a instanceof Pb){var b;if(null!=a&&(a.u&4096||a.Ab))b=a.Z;else throw Error([B("Doesn't support namespace: "),B(a)].join(""));return new V(b,$c.c?$c.c(a):$c.call(null,a),a.oa,null)}return"string"===typeof a?(b=a.split("/"),2===b.length?new V(b[0],b[1],a,null):new V(null,b[0],a,null)):null};Zc.a=function(a,b){return new V(a,b,[B(u(a)?[B(a),B("/")].join(""):null),B(b)].join(""),null)};Zc.R=2;
function W(a,b,c,d){this.l=a;this.Qa=b;this.v=c;this.m=d;this.j=32374988;this.u=0}f=W.prototype;f.toString=function(){return Cb(this)};f.equiv=function(a){return this.o(null,a)};function ad(a){null!=a.Qa&&(a.v=a.Qa.C?a.Qa.C():a.Qa.call(null),a.Qa=null);return a.v}f.H=function(){return this.l};f.$=function(){lb(this);return null==this.v?null:O(this.v)};f.F=function(){var a=this.m;return null!=a?a:this.m=a=Wb(this)};f.o=function(a,b){return ic(this,b)};f.T=function(a,b){return Mc(b,this)};
f.U=function(a,b,c){return Pc(b,c,this)};f.V=function(){lb(this);return null==this.v?null:M(this.v)};f.aa=function(){lb(this);return null!=this.v?N(this.v):Tb};f.P=function(){ad(this);if(null==this.v)return null;for(var a=this.v;;)if(a instanceof W)a=ad(a);else return this.v=a,J(this.v)};f.K=function(a,b){return new W(b,this.Qa,this.v,this.m)};f.M=function(a,b){return R(b,this)};W.prototype[Ha]=function(){return Q(this)};function bd(a,b){this.gb=a;this.end=b;this.j=2;this.u=0}
bd.prototype.add=function(a){this.gb[this.end]=a;return this.end+=1};bd.prototype.B=function(){var a=new cd(this.gb,0,this.end);this.gb=null;return a};bd.prototype.X=function(){return this.end};function dd(a){return new bd(Array(a),0)}function cd(a,b,c){this.b=a;this.L=b;this.end=c;this.j=524306;this.u=0}f=cd.prototype;f.X=function(){return this.end-this.L};f.N=function(a,b){return this.b[this.L+b]};f.da=function(a,b,c){return 0<=b&&b<this.end-this.L?this.b[this.L+b]:c};
f.ob=function(){if(this.L===this.end)throw Error("-drop-first of empty chunk");return new cd(this.b,this.L+1,this.end)};f.T=function(a,b){return dc(this.b,b,this.b[this.L],this.L+1)};f.U=function(a,b,c){return dc(this.b,b,c,this.L)};function ed(a,b,c,d){this.B=a;this.na=b;this.l=c;this.m=d;this.j=31850732;this.u=1536}f=ed.prototype;f.toString=function(){return Cb(this)};f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.l};
f.$=function(){if(1<Ka(this.B))return new ed(wb(this.B),this.na,this.l,null);var a=lb(this.na);return null==a?null:a};f.F=function(){var a=this.m;return null!=a?a:this.m=a=Wb(this)};f.o=function(a,b){return ic(this,b)};f.V=function(){return C.a(this.B,0)};f.aa=function(){return 1<Ka(this.B)?new ed(wb(this.B),this.na,this.l,null):null==this.na?Tb:this.na};f.P=function(){return this};f.ib=function(){return this.B};f.jb=function(){return null==this.na?Tb:this.na};
f.K=function(a,b){return new ed(this.B,this.na,b,this.m)};f.M=function(a,b){return R(b,this)};f.hb=function(){return null==this.na?null:this.na};ed.prototype[Ha]=function(){return Q(this)};function fd(a,b){return 0===Ka(a)?b:new ed(a,b,null,null)}function hd(a,b){a.add(b)}function Ic(a){for(var b=[];;)if(J(a))b.push(M(a)),a=O(a);else return b}function id(a,b){if(ec(a))return T(a);for(var c=a,d=b,e=0;;)if(0<d&&J(c))c=O(c),--d,e+=1;else return e}
var jd=function jd(b){return null==b?null:null==O(b)?J(M(b)):R(M(b),jd(O(b)))},kd=function kd(){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 0:return kd.C();case 1:return kd.c(arguments[0]);case 2:return kd.a(arguments[0],arguments[1]);default:return kd.w(arguments[0],arguments[1],new K(b.slice(2),0))}};kd.C=function(){return new W(null,function(){return null},null,null)};kd.c=function(a){return new W(null,function(){return a},null,null)};
kd.a=function(a,b){return new W(null,function(){var c=J(a);return c?zc(c)?fd(xb(c),kd.a(I(c),b)):R(M(c),kd.a(N(c),b)):b},null,null)};kd.w=function(a,b,c){return function e(a,b){return new W(null,function(){var c=J(a);return c?zc(c)?fd(xb(c),e(I(c),b)):R(M(c),e(N(c),b)):u(b)?e(M(b),O(b)):null},null,null)}(kd.a(a,b),c)};kd.I=function(a){var b=M(a),c=O(a);a=M(c);c=O(c);return kd.w(b,a,c)};kd.R=2;
var ld=function ld(){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 0:return ld.C();case 1:return ld.c(arguments[0]);case 2:return ld.a(arguments[0],arguments[1]);default:return ld.w(arguments[0],arguments[1],new K(b.slice(2),0))}};ld.C=function(){return pb(mc)};ld.c=function(a){return a};ld.a=function(a,b){return qb(a,b)};ld.w=function(a,b,c){for(;;)if(a=qb(a,b),u(c))b=M(c),c=O(c);else return a};
ld.I=function(a){var b=M(a),c=O(a);a=M(c);c=O(c);return ld.w(b,a,c)};ld.R=2;
function md(a,b,c){var d=J(c);if(0===b)return a.C?a.C():a.call(null);c=E(d);var e=G(d);if(1===b)return a.c?a.c(c):a.c?a.c(c):a.call(null,c);var d=E(e),g=G(e);if(2===b)return a.a?a.a(c,d):a.a?a.a(c,d):a.call(null,c,d);var e=E(g),h=G(g);if(3===b)return a.g?a.g(c,d,e):a.g?a.g(c,d,e):a.call(null,c,d,e);var g=E(h),k=G(h);if(4===b)return a.ca?a.ca(c,d,e,g):a.ca?a.ca(c,d,e,g):a.call(null,c,d,e,g);var h=E(k),l=G(k);if(5===b)return a.Y?a.Y(c,d,e,g,h):a.Y?a.Y(c,d,e,g,h):a.call(null,c,d,e,g,h);var k=E(l),m=
G(l);if(6===b)return a.Ba?a.Ba(c,d,e,g,h,k):a.Ba?a.Ba(c,d,e,g,h,k):a.call(null,c,d,e,g,h,k);var l=E(m),n=G(m);if(7===b)return a.Ca?a.Ca(c,d,e,g,h,k,l):a.Ca?a.Ca(c,d,e,g,h,k,l):a.call(null,c,d,e,g,h,k,l);var m=E(n),q=G(n);if(8===b)return a.Da?a.Da(c,d,e,g,h,k,l,m):a.Da?a.Da(c,d,e,g,h,k,l,m):a.call(null,c,d,e,g,h,k,l,m);var n=E(q),r=G(q);if(9===b)return a.Ea?a.Ea(c,d,e,g,h,k,l,m,n):a.Ea?a.Ea(c,d,e,g,h,k,l,m,n):a.call(null,c,d,e,g,h,k,l,m,n);var q=E(r),t=G(r);if(10===b)return a.qa?a.qa(c,d,e,g,h,k,l,
m,n,q):a.qa?a.qa(c,d,e,g,h,k,l,m,n,q):a.call(null,c,d,e,g,h,k,l,m,n,q);var r=E(t),w=G(t);if(11===b)return a.ra?a.ra(c,d,e,g,h,k,l,m,n,q,r):a.ra?a.ra(c,d,e,g,h,k,l,m,n,q,r):a.call(null,c,d,e,g,h,k,l,m,n,q,r);var t=E(w),x=G(w);if(12===b)return a.sa?a.sa(c,d,e,g,h,k,l,m,n,q,r,t):a.sa?a.sa(c,d,e,g,h,k,l,m,n,q,r,t):a.call(null,c,d,e,g,h,k,l,m,n,q,r,t);var w=E(x),z=G(x);if(13===b)return a.ta?a.ta(c,d,e,g,h,k,l,m,n,q,r,t,w):a.ta?a.ta(c,d,e,g,h,k,l,m,n,q,r,t,w):a.call(null,c,d,e,g,h,k,l,m,n,q,r,t,w);var x=
E(z),D=G(z);if(14===b)return a.ua?a.ua(c,d,e,g,h,k,l,m,n,q,r,t,w,x):a.ua?a.ua(c,d,e,g,h,k,l,m,n,q,r,t,w,x):a.call(null,c,d,e,g,h,k,l,m,n,q,r,t,w,x);var z=E(D),F=G(D);if(15===b)return a.va?a.va(c,d,e,g,h,k,l,m,n,q,r,t,w,x,z):a.va?a.va(c,d,e,g,h,k,l,m,n,q,r,t,w,x,z):a.call(null,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z);var D=E(F),L=G(F);if(16===b)return a.wa?a.wa(c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,D):a.wa?a.wa(c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,D):a.call(null,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,D);var F=E(L),ia=G(L);if(17===
b)return a.xa?a.xa(c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,D,F):a.xa?a.xa(c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,D,F):a.call(null,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,D,F);var L=E(ia),kb=G(ia);if(18===b)return a.ya?a.ya(c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,D,F,L):a.ya?a.ya(c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,D,F,L):a.call(null,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,D,F,L);ia=E(kb);kb=G(kb);if(19===b)return a.za?a.za(c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,D,F,L,ia):a.za?a.za(c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,D,F,L,ia):a.call(null,c,d,e,g,h,k,l,m,n,q,r,t,w,x,
z,D,F,L,ia);var A=E(kb);G(kb);if(20===b)return a.Aa?a.Aa(c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,D,F,L,ia,A):a.Aa?a.Aa(c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,D,F,L,ia,A):a.call(null,c,d,e,g,h,k,l,m,n,q,r,t,w,x,z,D,F,L,ia,A);throw Error("Only up to 20 arguments supported on functions");}
function sc(){for(var a=[],b=arguments.length,c=0;;)if(c<b)a.push(arguments[c]),c+=1;else break;switch(a.length){case 2:return nd(arguments[0],arguments[1]);case 3:return od(arguments[0],arguments[1],arguments[2]);case 4:b=arguments[0];a=R(arguments[1],R(arguments[2],arguments[3]));c=b.R;if(b.I)var d=id(a,c+1),b=d<=c?md(b,d,a):b.I(a);else b=b.apply(b,Ic(a));return b;case 5:return b=arguments[0],a=R(arguments[1],R(arguments[2],R(arguments[3],arguments[4]))),c=b.R,b.I?(d=id(a,c+1),b=d<=c?md(b,d,a):
b.I(a)):b=b.apply(b,Ic(a)),b;default:return b=arguments[0],a=R(arguments[1],R(arguments[2],R(arguments[3],R(arguments[4],jd(new K(a.slice(5),0)))))),c=b.R,b.I?(d=id(a,c+1),b=d<=c?md(b,d,a):b.I(a)):b=b.apply(b,Ic(a)),b}}function nd(a,b){var c=a.R;if(a.I){var d=id(b,c+1);return d<=c?md(a,d,b):a.I(b)}return a.apply(a,Ic(b))}function od(a,b,c){b=R(b,c);c=a.R;if(a.I){var d=id(b,c+1);return d<=c?md(a,d,b):a.I(b)}return a.apply(a,Ic(b))}
var pd=function pd(){"undefined"===typeof ma&&(ma=function(b,c){this.Fb=b;this.Eb=c;this.j=393216;this.u=0},ma.prototype.K=function(b,c){return new ma(this.Fb,c)},ma.prototype.H=function(){return this.Eb},ma.prototype.ha=function(){return!1},ma.prototype.next=function(){return Error("No such element")},ma.prototype.remove=function(){return Error("Unsupported operation")},ma.Nb=function(){return new X(null,2,5,qd,[tc(rd,new ua(null,1,[sd,Wc(td,Wc(mc))],null)),ud],null)},ma.sb=!0,ma.eb="cljs.core/t8622",
ma.Db=function(b){return H(b,"cljs.core/t8622")});return new ma(pd,vd)};function wd(a,b){for(;;){if(null==J(b))return!0;var c;c=M(b);c=a.c?a.c(c):a.call(null,c);if(u(c)){c=a;var d=O(b);a=c;b=d}else return!1}}function xd(a){for(var b=Rc;;)if(J(a)){var c;c=M(a);c=b.c?b.c(c):b.call(null,c);if(u(c))return c;a=O(a)}else return null}function yd(a,b){this.state=a;this.l=b;this.u=16386;this.j=6455296}yd.prototype.equiv=function(a){return this.o(null,a)};yd.prototype.o=function(a,b){return this===b};
yd.prototype.H=function(){return this.l};yd.prototype.F=function(){return this[ba]||(this[ba]=++da)};function zd(){for(var a=[],b=arguments.length,c=0;;)if(c<b)a.push(arguments[c]),c+=1;else break;switch(a.length){case 1:return Ad(arguments[0]);default:return b=arguments[0],a=new K(a.slice(1),0),a=null!=a&&(a.j&64||a.Ua)?nd(Bd,a):a,c=Sb(a,za),Sb(a,Cd),new yd(b,c)}}function Ad(a){return new yd(a,null)}
var Y=function Y(){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 1:return Y.c(arguments[0]);case 2:return Y.a(arguments[0],arguments[1]);case 3:return Y.g(arguments[0],arguments[1],arguments[2]);case 4:return Y.ca(arguments[0],arguments[1],arguments[2],arguments[3]);default:return Y.w(arguments[0],arguments[1],arguments[2],arguments[3],new K(b.slice(4),0))}};
Y.c=function(a){return function(b){return function(){function c(c,d){var e=a.c?a.c(d):a.call(null,d);return b.a?b.a(c,e):b.call(null,c,e)}function d(a){return b.c?b.c(a):b.call(null,a)}function e(){return b.C?b.C():b.call(null)}var g=null,h=function(){function c(a,b,e){var g=null;if(2<arguments.length){for(var g=0,h=Array(arguments.length-2);g<h.length;)h[g]=arguments[g+2],++g;g=new K(h,0)}return d.call(this,a,b,g)}function d(c,e,g){e=od(a,e,g);return b.a?b.a(c,e):b.call(null,c,e)}c.R=2;c.I=function(a){var b=
M(a);a=O(a);var c=M(a);a=N(a);return d(b,c,a)};c.w=d;return c}(),g=function(a,b,g){switch(arguments.length){case 0:return e.call(this);case 1:return d.call(this,a);case 2:return c.call(this,a,b);default:var n=null;if(2<arguments.length){for(var n=0,q=Array(arguments.length-2);n<q.length;)q[n]=arguments[n+2],++n;n=new K(q,0)}return h.w(a,b,n)}throw Error("Invalid arity: "+arguments.length);};g.R=2;g.I=h.I;g.C=e;g.c=d;g.a=c;g.w=h.w;return g}()}};
Y.a=function(a,b){return new W(null,function(){var c=J(b);if(c){if(zc(c)){for(var d=xb(c),e=T(d),g=dd(e),h=0;;)if(h<e)hd(g,function(){var b=C.a(d,h);return a.c?a.c(b):a.call(null,b)}()),h+=1;else break;return fd(g.B(),Y.a(a,I(c)))}return R(function(){var b=M(c);return a.c?a.c(b):a.call(null,b)}(),Y.a(a,N(c)))}return null},null,null)};
Y.g=function(a,b,c){return new W(null,function(){var d=J(b),e=J(c);if(d&&e){var g=R,h;h=M(d);var k=M(e);h=a.a?a.a(h,k):a.call(null,h,k);d=g(h,Y.g(a,N(d),N(e)))}else d=null;return d},null,null)};Y.ca=function(a,b,c,d){return new W(null,function(){var e=J(b),g=J(c),h=J(d);if(e&&g&&h){var k=R,l;l=M(e);var m=M(g),n=M(h);l=a.g?a.g(l,m,n):a.call(null,l,m,n);e=k(l,Y.ca(a,N(e),N(g),N(h)))}else e=null;return e},null,null)};
Y.w=function(a,b,c,d,e){var g=function k(a){return new W(null,function(){var b=Y.a(J,a);return wd(Rc,b)?R(Y.a(M,b),k(Y.a(N,b))):null},null,null)};return Y.a(function(){return function(b){return nd(a,b)}}(g),g(S.w(e,d,kc([c,b],0))))};Y.I=function(a){var b=M(a),c=O(a);a=M(c);var d=O(c),c=M(d),e=O(d),d=M(e),e=O(e);return Y.w(b,a,c,d,e)};Y.R=4;
function Dd(a,b){if("number"!==typeof a)throw Error([B("Assert failed: "),B(function(){var a=Wc(Ed,Fd);return Gd.c?Gd.c(a):Gd.call(null,a)}())].join(""));return new W(null,function(){if(0<a){var c=J(b);return c?R(M(c),Dd(a-1,N(c))):null}return null},null,null)}function Hd(a){return new W(null,function(){return R(a,Hd(a))},null,null)}
function Id(a,b){return new W(null,function(){var c=J(b);if(c){if(zc(c)){for(var d=xb(c),e=T(d),g=dd(e),h=0;;)if(h<e){var k;k=C.a(d,h);k=a.c?a.c(k):a.call(null,k);u(k)&&(k=C.a(d,h),g.add(k));h+=1}else break;return fd(g.B(),Id(a,I(c)))}d=M(c);c=N(c);return u(a.c?a.c(d):a.call(null,d))?R(d,Id(a,c)):Id(a,c)}return null},null,null)}function Jd(a,b){var c;null!=a?null!=a&&(a.u&4||a.Ib)?(c=Nc(qb,pb(a),b),c=rb(c),c=tc(c,uc(a))):c=Nc(La,a,b):c=Nc(S,Tb,b);return c}function Kd(a,b){this.A=a;this.b=b}
function Ld(a){return new Kd(a,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null])}function Md(a){return new Kd(a.A,Ia(a.b))}function Nd(a){a=a.h;return 32>a?0:a-1>>>5<<5}function Od(a,b,c){for(;;){if(0===b)return c;var d=Ld(a);d.b[0]=c;c=d;b-=5}}var Pd=function Pd(b,c,d,e){var g=Md(d),h=b.h-1>>>c&31;5===c?g.b[h]=e:(d=d.b[h],b=null!=d?Pd(b,c-5,d,e):Od(null,c-5,e),g.b[h]=b);return g};
function Qd(a,b){throw Error([B("No item "),B(a),B(" in vector of length "),B(b)].join(""));}function Rd(a,b){if(b>=Nd(a))return a.W;for(var c=a.root,d=a.shift;;)if(0<d)var e=d-5,c=c.b[b>>>d&31],d=e;else return c.b}function Sd(a,b){return 0<=b&&b<a.h?Rd(a,b):Qd(b,a.h)}
var Td=function Td(b,c,d,e,g){var h=Md(d);if(0===c)h.b[e&31]=g;else{var k=e>>>c&31;b=Td(b,c-5,d.b[k],e,g);h.b[k]=b}return h},Ud=function Ud(b,c,d){var e=b.h-2>>>c&31;if(5<c){b=Ud(b,c-5,d.b[e]);if(null==b&&0===e)return null;d=Md(d);d.b[e]=b;return d}if(0===e)return null;d=Md(d);d.b[e]=null;return d};function Vd(a,b,c,d,e,g){this.i=a;this.fb=b;this.b=c;this.ia=d;this.start=e;this.end=g}Vd.prototype.ha=function(){return this.i<this.end};
Vd.prototype.next=function(){32===this.i-this.fb&&(this.b=Rd(this.ia,this.i),this.fb+=32);var a=this.b[this.i&31];this.i+=1;return a};function X(a,b,c,d,e,g){this.l=a;this.h=b;this.shift=c;this.root=d;this.W=e;this.m=g;this.j=167668511;this.u=8196}f=X.prototype;f.toString=function(){return Cb(this)};f.equiv=function(a){return this.o(null,a)};f.S=function(a,b){return Qa.g(this,b,null)};f.G=function(a,b,c){return"number"===typeof b?C.g(this,b,c):c};f.N=function(a,b){return Sd(this,b)[b&31]};
f.da=function(a,b,c){return 0<=b&&b<this.h?Rd(this,b)[b&31]:c};f.mb=function(a,b,c){if(0<=b&&b<this.h)return Nd(this)<=b?(a=Ia(this.W),a[b&31]=c,new X(this.l,this.h,this.shift,this.root,a,null)):new X(this.l,this.h,this.shift,Td(this,this.shift,this.root,b,c),this.W,null);if(b===this.h)return La(this,c);throw Error([B("Index "),B(b),B(" out of bounds  [0,"),B(this.h),B("]")].join(""));};f.Fa=function(){var a=this.h;return new Vd(0,0,0<T(this)?Rd(this,0):null,this,0,a)};f.H=function(){return this.l};
f.X=function(){return this.h};f.kb=function(){return C.a(this,0)};f.lb=function(){return C.a(this,1)};f.Va=function(){return 0<this.h?C.a(this,this.h-1):null};
f.Wa=function(){if(0===this.h)throw Error("Can't pop empty vector");if(1===this.h)return db(mc,this.l);if(1<this.h-Nd(this))return new X(this.l,this.h-1,this.shift,this.root,this.W.slice(0,-1),null);var a=Rd(this,this.h-2),b=Ud(this,this.shift,this.root),b=null==b?qd:b,c=this.h-1;return 5<this.shift&&null==b.b[1]?new X(this.l,c,this.shift-5,b.b[0],a,null):new X(this.l,c,this.shift,b,a,null)};f.F=function(){var a=this.m;return null!=a?a:this.m=a=Wb(this)};
f.o=function(a,b){if(b instanceof X)if(this.h===T(b))for(var c=Ab(this),d=Ab(b);;)if(u(c.ha())){var e=c.next(),g=d.next();if(!P.a(e,g))return!1}else return!0;else return!1;else return ic(this,b)};f.Ta=function(){return new Wd(this.h,this.shift,Xd.c?Xd.c(this.root):Xd.call(null,this.root),Yd.c?Yd.c(this.W):Yd.call(null,this.W))};f.T=function(a,b){return $b(this,b)};
f.U=function(a,b,c){a=0;for(var d=c;;)if(a<this.h){var e=Rd(this,a);c=e.length;a:for(var g=0;;)if(g<c)var h=e[g],d=b.a?b.a(d,h):b.call(null,d,h),g=g+1;else{e=d;break a}a+=c;d=e}else return d};f.Ra=function(a,b,c){if("number"===typeof b)return ab(this,b,c);throw Error("Vector's key for assoc must be a number.");};
f.P=function(){if(0===this.h)return null;if(32>=this.h)return new K(this.W,0);var a;a:{a=this.root;for(var b=this.shift;;)if(0<b)b-=5,a=a.b[0];else{a=a.b;break a}}return Zd?Zd(this,a,0,0):$d.call(null,this,a,0,0)};f.K=function(a,b){return new X(b,this.h,this.shift,this.root,this.W,this.m)};
f.M=function(a,b){if(32>this.h-Nd(this)){for(var c=this.W.length,d=Array(c+1),e=0;;)if(e<c)d[e]=this.W[e],e+=1;else break;d[c]=b;return new X(this.l,this.h+1,this.shift,this.root,d,null)}c=(d=this.h>>>5>1<<this.shift)?this.shift+5:this.shift;d?(d=Ld(null),d.b[0]=this.root,e=Od(null,this.shift,new Kd(null,this.W)),d.b[1]=e):d=Pd(this,this.shift,this.root,new Kd(null,this.W));return new X(this.l,this.h+1,c,d,[b],null)};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.N(null,c);case 3:return this.da(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.a=function(a,c){return this.N(null,c)};a.g=function(a,c,d){return this.da(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ia(b)))};f.c=function(a){return this.N(null,a)};f.a=function(a,b){return this.da(null,a,b)};
var qd=new Kd(null,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]),mc=new X(null,0,5,qd,[],Xb);function ae(a){var b=a.length;if(32>b)return new X(null,b,5,qd,a,null);for(var c=32,d=(new X(null,32,5,qd,a.slice(0,32),null)).Ta(null);;)if(c<b)var e=c+1,d=ld.a(d,a[c]),c=e;else return rb(d)}X.prototype[Ha]=function(){return Q(this)};function be(a){return Da(a)?ae(a):rb(Nc(qb,pb(mc),a))}
var ce=function ce(){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;return ce.w(0<b.length?new K(b.slice(0),0):null)};ce.w=function(a){return a instanceof K&&0===a.i?ae(a.b):be(a)};ce.R=0;ce.I=function(a){return ce.w(J(a))};function de(a,b,c,d,e,g){this.fa=a;this.node=b;this.i=c;this.L=d;this.l=e;this.m=g;this.j=32375020;this.u=1536}f=de.prototype;f.toString=function(){return Cb(this)};f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.l};
f.$=function(){if(this.L+1<this.node.length){var a;a=this.fa;var b=this.node,c=this.i,d=this.L+1;a=Zd?Zd(a,b,c,d):$d.call(null,a,b,c,d);return null==a?null:a}return yb(this)};f.F=function(){var a=this.m;return null!=a?a:this.m=a=Wb(this)};f.o=function(a,b){return ic(this,b)};f.T=function(a,b){var c;c=this.fa;var d=this.i+this.L,e=T(this.fa);c=ee?ee(c,d,e):fe.call(null,c,d,e);return $b(c,b)};
f.U=function(a,b,c){a=this.fa;var d=this.i+this.L,e=T(this.fa);a=ee?ee(a,d,e):fe.call(null,a,d,e);return ac(a,b,c)};f.V=function(){return this.node[this.L]};f.aa=function(){if(this.L+1<this.node.length){var a;a=this.fa;var b=this.node,c=this.i,d=this.L+1;a=Zd?Zd(a,b,c,d):$d.call(null,a,b,c,d);return null==a?Tb:a}return I(this)};f.P=function(){return this};f.ib=function(){var a=this.node;return new cd(a,this.L,a.length)};
f.jb=function(){var a=this.i+this.node.length;if(a<Ka(this.fa)){var b=this.fa,c=Rd(this.fa,a);return Zd?Zd(b,c,a,0):$d.call(null,b,c,a,0)}return Tb};f.K=function(a,b){return ge?ge(this.fa,this.node,this.i,this.L,b):$d.call(null,this.fa,this.node,this.i,this.L,b)};f.M=function(a,b){return R(b,this)};f.hb=function(){var a=this.i+this.node.length;if(a<Ka(this.fa)){var b=this.fa,c=Rd(this.fa,a);return Zd?Zd(b,c,a,0):$d.call(null,b,c,a,0)}return null};de.prototype[Ha]=function(){return Q(this)};
function $d(){for(var a=[],b=arguments.length,c=0;;)if(c<b)a.push(arguments[c]),c+=1;else break;switch(a.length){case 3:return a=arguments[0],b=arguments[1],c=arguments[2],new de(a,Sd(a,b),b,c,null,null);case 4:return Zd(arguments[0],arguments[1],arguments[2],arguments[3]);case 5:return ge(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);default:throw Error([B("Invalid arity: "),B(a.length)].join(""));}}function Zd(a,b,c,d){return new de(a,b,c,d,null,null)}
function ge(a,b,c,d,e){return new de(a,b,c,d,e,null)}function he(a,b,c,d,e){this.l=a;this.ia=b;this.start=c;this.end=d;this.m=e;this.j=167666463;this.u=8192}f=he.prototype;f.toString=function(){return Cb(this)};f.equiv=function(a){return this.o(null,a)};f.S=function(a,b){return Qa.g(this,b,null)};f.G=function(a,b,c){return"number"===typeof b?C.g(this,b,c):c};f.N=function(a,b){return 0>b||this.end<=this.start+b?Qd(b,this.end-this.start):C.a(this.ia,this.start+b)};
f.da=function(a,b,c){return 0>b||this.end<=this.start+b?c:C.g(this.ia,this.start+b,c)};f.mb=function(a,b,c){var d=this.start+b;a=this.l;c=pc.g(this.ia,d,c);b=this.start;var e=this.end,d=d+1,d=e>d?e:d;return ie.Y?ie.Y(a,c,b,d,null):ie.call(null,a,c,b,d,null)};f.H=function(){return this.l};f.X=function(){return this.end-this.start};f.Va=function(){return C.a(this.ia,this.end-1)};
f.Wa=function(){if(this.start===this.end)throw Error("Can't pop empty vector");var a=this.l,b=this.ia,c=this.start,d=this.end-1;return ie.Y?ie.Y(a,b,c,d,null):ie.call(null,a,b,c,d,null)};f.F=function(){var a=this.m;return null!=a?a:this.m=a=Wb(this)};f.o=function(a,b){return ic(this,b)};f.T=function(a,b){return $b(this,b)};f.U=function(a,b,c){return ac(this,b,c)};f.Ra=function(a,b,c){if("number"===typeof b)return ab(this,b,c);throw Error("Subvec's key for assoc must be a number.");};
f.P=function(){var a=this;return function(b){return function d(e){return e===a.end?null:R(C.a(a.ia,e),new W(null,function(){return function(){return d(e+1)}}(b),null,null))}}(this)(a.start)};f.K=function(a,b){return ie.Y?ie.Y(b,this.ia,this.start,this.end,this.m):ie.call(null,b,this.ia,this.start,this.end,this.m)};f.M=function(a,b){var c=this.l,d=ab(this.ia,this.end,b),e=this.start,g=this.end+1;return ie.Y?ie.Y(c,d,e,g,null):ie.call(null,c,d,e,g,null)};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.N(null,c);case 3:return this.da(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.a=function(a,c){return this.N(null,c)};a.g=function(a,c,d){return this.da(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ia(b)))};f.c=function(a){return this.N(null,a)};f.a=function(a,b){return this.da(null,a,b)};he.prototype[Ha]=function(){return Q(this)};
function ie(a,b,c,d,e){for(;;)if(b instanceof he)c=b.start+c,d=b.start+d,b=b.ia;else{var g=T(b);if(0>c||0>d||c>g||d>g)throw Error("Index out of bounds");return new he(a,b,c,d,e)}}function fe(){for(var a=[],b=arguments.length,c=0;;)if(c<b)a.push(arguments[c]),c+=1;else break;switch(a.length){case 2:return a=arguments[0],ee(a,arguments[1],T(a));case 3:return ee(arguments[0],arguments[1],arguments[2]);default:throw Error([B("Invalid arity: "),B(a.length)].join(""));}}
function ee(a,b,c){return ie(null,a,b,c,null)}function ke(a,b){return a===b.A?b:new Kd(a,Ia(b.b))}function Xd(a){return new Kd({},Ia(a.b))}function Yd(a){var b=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];Bc(a,0,b,0,a.length);return b}var le=function le(b,c,d,e){d=ke(b.root.A,d);var g=b.h-1>>>c&31;if(5===c)b=e;else{var h=d.b[g];b=null!=h?le(b,c-5,h,e):Od(b.root.A,c-5,e)}d.b[g]=b;return d};
function Wd(a,b,c,d){this.h=a;this.shift=b;this.root=c;this.W=d;this.u=88;this.j=275}f=Wd.prototype;
f.bb=function(a,b){if(this.root.A){if(32>this.h-Nd(this))this.W[this.h&31]=b;else{var c=new Kd(this.root.A,this.W),d=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];d[0]=b;this.W=d;if(this.h>>>5>1<<this.shift){var d=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],e=this.shift+
5;d[0]=this.root;d[1]=Od(this.root.A,this.shift,c);this.root=new Kd(this.root.A,d);this.shift=e}else this.root=le(this,this.shift,this.root,c)}this.h+=1;return this}throw Error("conj! after persistent!");};f.cb=function(){if(this.root.A){this.root.A=null;var a=this.h-Nd(this),b=Array(a);Bc(this.W,0,b,0,a);return new X(null,this.h,this.shift,this.root,b,null)}throw Error("persistent! called twice");};
f.Xa=function(a,b,c){if("number"===typeof b)return tb(this,b,c);throw Error("TransientVector's key for assoc! must be a number.");};
f.qb=function(a,b,c){var d=this;if(d.root.A){if(0<=b&&b<d.h)return Nd(this)<=b?d.W[b&31]=c:(a=function(){return function g(a,k){var l=ke(d.root.A,k);if(0===a)l.b[b&31]=c;else{var m=b>>>a&31,n=g(a-5,l.b[m]);l.b[m]=n}return l}}(this).call(null,d.shift,d.root),d.root=a),this;if(b===d.h)return qb(this,c);throw Error([B("Index "),B(b),B(" out of bounds for TransientVector of length"),B(d.h)].join(""));}throw Error("assoc! after persistent!");};
f.X=function(){if(this.root.A)return this.h;throw Error("count after persistent!");};f.N=function(a,b){if(this.root.A)return Sd(this,b)[b&31];throw Error("nth after persistent!");};f.da=function(a,b,c){return 0<=b&&b<this.h?C.a(this,b):c};f.S=function(a,b){return Qa.g(this,b,null)};f.G=function(a,b,c){return"number"===typeof b?C.g(this,b,c):c};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.S(null,c);case 3:return this.G(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.a=function(a,c){return this.S(null,c)};a.g=function(a,c,d){return this.G(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ia(b)))};f.c=function(a){return this.S(null,a)};f.a=function(a,b){return this.G(null,a,b)};function me(){this.j=2097152;this.u=0}
me.prototype.equiv=function(a){return this.o(null,a)};me.prototype.o=function(){return!1};var ne=new me;function oe(a,b){return Dc(xc(b)?T(a)===T(b)?wd(Rc,Y.a(function(a){return P.a(Qb(b,M(a),ne),lc(a))},a)):null:null)}function pe(a){this.v=a}pe.prototype.next=function(){if(null!=this.v){var a=M(this.v),b=U(a,0),a=U(a,1);this.v=O(this.v);return{value:[b,a],done:!1}}return{value:null,done:!0}};function qe(a){return new pe(J(a))}
function re(a,b){var c;if(b instanceof V)a:{c=a.length;for(var d=b.ma,e=0;;){if(c<=e){c=-1;break a}if(a[e]instanceof V&&d===a[e].ma){c=e;break a}e+=2}}else if("string"==typeof b||"number"===typeof b)a:for(c=a.length,d=0;;){if(c<=d){c=-1;break a}if(b===a[d]){c=d;break a}d+=2}else if(b instanceof Pb)a:for(c=a.length,d=b.oa,e=0;;){if(c<=e){c=-1;break a}if(a[e]instanceof Pb&&d===a[e].oa){c=e;break a}e+=2}else if(null==b)a:for(c=a.length,d=0;;){if(c<=d){c=-1;break a}if(null==a[d]){c=d;break a}d+=2}else a:for(c=
a.length,d=0;;){if(c<=d){c=-1;break a}if(P.a(b,a[d])){c=d;break a}d+=2}return c}function se(a,b,c){this.b=a;this.i=b;this.ga=c;this.j=32374990;this.u=0}f=se.prototype;f.toString=function(){return Cb(this)};f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.ga};f.$=function(){return this.i<this.b.length-2?new se(this.b,this.i+2,this.ga):null};f.X=function(){return(this.b.length-this.i)/2};f.F=function(){return Wb(this)};f.o=function(a,b){return ic(this,b)};
f.T=function(a,b){return Mc(b,this)};f.U=function(a,b,c){return Pc(b,c,this)};f.V=function(){return new X(null,2,5,qd,[this.b[this.i],this.b[this.i+1]],null)};f.aa=function(){return this.i<this.b.length-2?new se(this.b,this.i+2,this.ga):Tb};f.P=function(){return this};f.K=function(a,b){return new se(this.b,this.i,b)};f.M=function(a,b){return R(b,this)};se.prototype[Ha]=function(){return Q(this)};function te(a,b,c){this.b=a;this.i=b;this.h=c}te.prototype.ha=function(){return this.i<this.h};
te.prototype.next=function(){var a=new X(null,2,5,qd,[this.b[this.i],this.b[this.i+1]],null);this.i+=2;return a};function ua(a,b,c,d){this.l=a;this.h=b;this.b=c;this.m=d;this.j=16647951;this.u=8196}f=ua.prototype;f.toString=function(){return Cb(this)};f.equiv=function(a){return this.o(null,a)};f.keys=function(){return Q(ue.c?ue.c(this):ue.call(null,this))};f.entries=function(){return qe(J(this))};f.values=function(){return Q(ve.c?ve.c(this):ve.call(null,this))};
f.has=function(a){return Qb(this,a,Cc)===Cc?!1:!0};f.get=function(a,b){return this.G(null,a,b)};f.forEach=function(a){for(var b=J(this),c=null,d=0,e=0;;)if(e<d){var g=c.N(null,e),h=U(g,0),g=U(g,1);a.a?a.a(g,h):a.call(null,g,h);e+=1}else if(b=J(b))zc(b)?(c=xb(b),b=I(b),h=c,d=T(c),c=h):(c=M(b),h=U(c,0),g=U(c,1),a.a?a.a(g,h):a.call(null,g,h),b=O(b),c=null,d=0),e=0;else return null};f.S=function(a,b){return Qa.g(this,b,null)};f.G=function(a,b,c){a=re(this.b,b);return-1===a?c:this.b[a+1]};
f.Fa=function(){return new te(this.b,0,2*this.h)};f.H=function(){return this.l};f.X=function(){return this.h};f.F=function(){var a=this.m;return null!=a?a:this.m=a=Yb(this)};f.o=function(a,b){if(null!=b&&(b.j&1024||b.xb)){var c=this.b.length;if(this.h===b.X(null))for(var d=0;;)if(d<c){var e=b.G(null,this.b[d],Cc);if(e!==Cc)if(P.a(this.b[d+1],e))d+=2;else return!1;else return!1}else return!0;else return!1}else return oe(this,b)};f.Ta=function(){return new we({},this.b.length,Ia(this.b))};
f.T=function(a,b){return Mc(b,this)};f.U=function(a,b,c){return Pc(b,c,this)};f.Ra=function(a,b,c){a=re(this.b,b);if(-1===a){if(this.h<xe){a=this.b;for(var d=a.length,e=Array(d+2),g=0;;)if(g<d)e[g]=a[g],g+=1;else break;e[d]=b;e[d+1]=c;return new ua(this.l,this.h+1,e,null)}return db(Ra(Jd(qc,this),b,c),this.l)}if(c===this.b[a+1])return this;b=Ia(this.b);b[a+1]=c;return new ua(this.l,this.h,b,null)};f.P=function(){var a=this.b;return 0<=a.length-2?new se(a,0,null):null};
f.K=function(a,b){return new ua(b,this.h,this.b,this.m)};f.M=function(a,b){if(yc(b))return Ra(this,C.a(b,0),C.a(b,1));for(var c=this,d=J(b);;){if(null==d)return c;var e=M(d);if(yc(e))c=Ra(c,C.a(e,0),C.a(e,1)),d=O(d);else throw Error("conj on a map takes map entries or seqables of map entries");}};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.S(null,c);case 3:return this.G(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.a=function(a,c){return this.S(null,c)};a.g=function(a,c,d){return this.G(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ia(b)))};f.c=function(a){return this.S(null,a)};f.a=function(a,b){return this.G(null,a,b)};var vd=new ua(null,0,[],Zb),xe=8;
function ye(a){for(var b=[],c=0;;)if(c<a.length){var d=a[c],e=a[c+1];-1===re(b,d)&&(b.push(d),b.push(e));c+=2}else break;return new ua(null,b.length/2,b,null)}ua.prototype[Ha]=function(){return Q(this)};function we(a,b,c){this.Pa=a;this.Ma=b;this.b=c;this.j=258;this.u=56}f=we.prototype;f.X=function(){if(u(this.Pa))return Sc(this.Ma);throw Error("count after persistent!");};f.S=function(a,b){return Qa.g(this,b,null)};
f.G=function(a,b,c){if(u(this.Pa))return a=re(this.b,b),-1===a?c:this.b[a+1];throw Error("lookup after persistent!");};f.bb=function(a,b){if(u(this.Pa)){if(null!=b?b.j&2048||b.yb||(b.j?0:v(Ua,b)):v(Ua,b))return sb(this,ze.c?ze.c(b):ze.call(null,b),Ae.c?Ae.c(b):Ae.call(null,b));for(var c=J(b),d=this;;){var e=M(c);if(u(e))c=O(c),d=sb(d,ze.c?ze.c(e):ze.call(null,e),Ae.c?Ae.c(e):Ae.call(null,e));else return d}}else throw Error("conj! after persistent!");};
f.cb=function(){if(u(this.Pa))return this.Pa=!1,new ua(null,Sc(this.Ma),this.b,null);throw Error("persistent! called twice");};f.Xa=function(a,b,c){if(u(this.Pa)){a=re(this.b,b);if(-1===a){if(this.Ma+2<=2*xe)return this.Ma+=2,this.b.push(b),this.b.push(c),this;a=Be.a?Be.a(this.Ma,this.b):Be.call(null,this.Ma,this.b);return sb(a,b,c)}c!==this.b[a+1]&&(this.b[a+1]=c);return this}throw Error("assoc! after persistent!");};
function Be(a,b){for(var c=pb(qc),d=0;;)if(d<a)c=sb(c,b[d],b[d+1]),d+=2;else return c}function Ce(){this.pa=!1}function De(a,b){return a===b?!0:a===b||a instanceof V&&b instanceof V&&a.ma===b.ma?!0:P.a(a,b)}function Ee(a,b,c){a=Ia(a);a[b]=c;return a}function Fe(a,b,c,d){a=a.Ka(b);a.b[c]=d;return a}function Ge(a,b,c,d){this.b=a;this.i=b;this.Za=c;this.la=d}
Ge.prototype.advance=function(){for(var a=this.b.length;;)if(this.i<a){var b=this.b[this.i],c=this.b[this.i+1];null!=b?b=this.Za=new X(null,2,5,qd,[b,c],null):null!=c?(b=Ab(c),b=b.ha()?this.la=b:!1):b=!1;this.i+=2;if(b)return!0}else return!1};Ge.prototype.ha=function(){var a=null!=this.Za;return a?a:(a=null!=this.la)?a:this.advance()};
Ge.prototype.next=function(){if(null!=this.Za){var a=this.Za;this.Za=null;return a}if(null!=this.la)return a=this.la.next(),this.la.ha()||(this.la=null),a;if(this.advance())return this.next();throw Error("No such element");};Ge.prototype.remove=function(){return Error("Unsupported operation")};function He(a,b,c){this.A=a;this.J=b;this.b=c}f=He.prototype;f.Ka=function(a){if(a===this.A)return this;var b=Tc(this.J),c=Array(0>b?4:2*(b+1));Bc(this.b,0,c,0,2*b);return new He(a,this.J,c)};
f.Ya=function(){return Ie?Ie(this.b):Je.call(null,this.b)};f.La=function(a,b,c,d){var e=1<<(b>>>a&31);if(0===(this.J&e))return d;var g=Tc(this.J&e-1),e=this.b[2*g],g=this.b[2*g+1];return null==e?g.La(a+5,b,c,d):De(c,e)?g:d};
f.ka=function(a,b,c,d,e,g){var h=1<<(c>>>b&31),k=Tc(this.J&h-1);if(0===(this.J&h)){var l=Tc(this.J);if(2*l<this.b.length){a=this.Ka(a);b=a.b;g.pa=!0;a:for(c=2*(l-k),g=2*k+(c-1),l=2*(k+1)+(c-1);;){if(0===c)break a;b[l]=b[g];--l;--c;--g}b[2*k]=d;b[2*k+1]=e;a.J|=h;return a}if(16<=l){k=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];k[c>>>b&31]=Ke.ka(a,b+5,c,d,e,g);for(e=d=0;;)if(32>d)0!==
(this.J>>>d&1)&&(k[d]=null!=this.b[e]?Ke.ka(a,b+5,Lb(this.b[e]),this.b[e],this.b[e+1],g):this.b[e+1],e+=2),d+=1;else break;return new Le(a,l+1,k)}b=Array(2*(l+4));Bc(this.b,0,b,0,2*k);b[2*k]=d;b[2*k+1]=e;Bc(this.b,2*k,b,2*(k+1),2*(l-k));g.pa=!0;a=this.Ka(a);a.b=b;a.J|=h;return a}l=this.b[2*k];h=this.b[2*k+1];if(null==l)return l=h.ka(a,b+5,c,d,e,g),l===h?this:Fe(this,a,2*k+1,l);if(De(d,l))return e===h?this:Fe(this,a,2*k+1,e);g.pa=!0;g=b+5;d=Me?Me(a,g,l,h,c,d,e):Ne.call(null,a,g,l,h,c,d,e);e=2*k;k=
2*k+1;a=this.Ka(a);a.b[e]=null;a.b[k]=d;return a};
f.ja=function(a,b,c,d,e){var g=1<<(b>>>a&31),h=Tc(this.J&g-1);if(0===(this.J&g)){var k=Tc(this.J);if(16<=k){h=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];h[b>>>a&31]=Ke.ja(a+5,b,c,d,e);for(d=c=0;;)if(32>c)0!==(this.J>>>c&1)&&(h[c]=null!=this.b[d]?Ke.ja(a+5,Lb(this.b[d]),this.b[d],this.b[d+1],e):this.b[d+1],d+=2),c+=1;else break;return new Le(null,k+1,h)}a=Array(2*(k+1));Bc(this.b,
0,a,0,2*h);a[2*h]=c;a[2*h+1]=d;Bc(this.b,2*h,a,2*(h+1),2*(k-h));e.pa=!0;return new He(null,this.J|g,a)}var l=this.b[2*h],g=this.b[2*h+1];if(null==l)return k=g.ja(a+5,b,c,d,e),k===g?this:new He(null,this.J,Ee(this.b,2*h+1,k));if(De(c,l))return d===g?this:new He(null,this.J,Ee(this.b,2*h+1,d));e.pa=!0;e=this.J;k=this.b;a+=5;a=Oe?Oe(a,l,g,b,c,d):Ne.call(null,a,l,g,b,c,d);c=2*h;h=2*h+1;d=Ia(k);d[c]=null;d[h]=a;return new He(null,e,d)};f.Fa=function(){return new Ge(this.b,0,null,null)};
var Ke=new He(null,0,[]);function Pe(a,b,c){this.b=a;this.i=b;this.la=c}Pe.prototype.ha=function(){for(var a=this.b.length;;){if(null!=this.la&&this.la.ha())return!0;if(this.i<a){var b=this.b[this.i];this.i+=1;null!=b&&(this.la=Ab(b))}else return!1}};Pe.prototype.next=function(){if(this.ha())return this.la.next();throw Error("No such element");};Pe.prototype.remove=function(){return Error("Unsupported operation")};function Le(a,b,c){this.A=a;this.h=b;this.b=c}f=Le.prototype;
f.Ka=function(a){return a===this.A?this:new Le(a,this.h,Ia(this.b))};f.Ya=function(){return Qe?Qe(this.b):Re.call(null,this.b)};f.La=function(a,b,c,d){var e=this.b[b>>>a&31];return null!=e?e.La(a+5,b,c,d):d};f.ka=function(a,b,c,d,e,g){var h=c>>>b&31,k=this.b[h];if(null==k)return a=Fe(this,a,h,Ke.ka(a,b+5,c,d,e,g)),a.h+=1,a;b=k.ka(a,b+5,c,d,e,g);return b===k?this:Fe(this,a,h,b)};
f.ja=function(a,b,c,d,e){var g=b>>>a&31,h=this.b[g];if(null==h)return new Le(null,this.h+1,Ee(this.b,g,Ke.ja(a+5,b,c,d,e)));a=h.ja(a+5,b,c,d,e);return a===h?this:new Le(null,this.h,Ee(this.b,g,a))};f.Fa=function(){return new Pe(this.b,0,null)};function Se(a,b,c){b*=2;for(var d=0;;)if(d<b){if(De(c,a[d]))return d;d+=2}else return-1}function Te(a,b,c,d){this.A=a;this.Ha=b;this.h=c;this.b=d}f=Te.prototype;
f.Ka=function(a){if(a===this.A)return this;var b=Array(2*(this.h+1));Bc(this.b,0,b,0,2*this.h);return new Te(a,this.Ha,this.h,b)};f.Ya=function(){return Ie?Ie(this.b):Je.call(null,this.b)};f.La=function(a,b,c,d){a=Se(this.b,this.h,c);return 0>a?d:De(c,this.b[a])?this.b[a+1]:d};
f.ka=function(a,b,c,d,e,g){if(c===this.Ha){b=Se(this.b,this.h,d);if(-1===b){if(this.b.length>2*this.h)return b=2*this.h,c=2*this.h+1,a=this.Ka(a),a.b[b]=d,a.b[c]=e,g.pa=!0,a.h+=1,a;c=this.b.length;b=Array(c+2);Bc(this.b,0,b,0,c);b[c]=d;b[c+1]=e;g.pa=!0;d=this.h+1;a===this.A?(this.b=b,this.h=d,a=this):a=new Te(this.A,this.Ha,d,b);return a}return this.b[b+1]===e?this:Fe(this,a,b+1,e)}return(new He(a,1<<(this.Ha>>>b&31),[null,this,null,null])).ka(a,b,c,d,e,g)};
f.ja=function(a,b,c,d,e){return b===this.Ha?(a=Se(this.b,this.h,c),-1===a?(a=2*this.h,b=Array(a+2),Bc(this.b,0,b,0,a),b[a]=c,b[a+1]=d,e.pa=!0,new Te(null,this.Ha,this.h+1,b)):P.a(this.b[a],d)?this:new Te(null,this.Ha,this.h,Ee(this.b,a+1,d))):(new He(null,1<<(this.Ha>>>a&31),[null,this])).ja(a,b,c,d,e)};f.Fa=function(){return new Ge(this.b,0,null,null)};
function Ne(){for(var a=[],b=arguments.length,c=0;;)if(c<b)a.push(arguments[c]),c+=1;else break;switch(a.length){case 6:return Oe(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5]);case 7:return Me(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6]);default:throw Error([B("Invalid arity: "),B(a.length)].join(""));}}
function Oe(a,b,c,d,e,g){var h=Lb(b);if(h===d)return new Te(null,h,2,[b,c,e,g]);var k=new Ce;return Ke.ja(a,h,b,c,k).ja(a,d,e,g,k)}function Me(a,b,c,d,e,g,h){var k=Lb(c);if(k===e)return new Te(null,k,2,[c,d,g,h]);var l=new Ce;return Ke.ka(a,b,k,c,d,l).ka(a,b,e,g,h,l)}function Ue(a,b,c,d,e){this.l=a;this.Ia=b;this.i=c;this.v=d;this.m=e;this.j=32374860;this.u=0}f=Ue.prototype;f.toString=function(){return Cb(this)};f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.l};
f.F=function(){var a=this.m;return null!=a?a:this.m=a=Wb(this)};f.o=function(a,b){return ic(this,b)};f.T=function(a,b){return Mc(b,this)};f.U=function(a,b,c){return Pc(b,c,this)};f.V=function(){return null==this.v?new X(null,2,5,qd,[this.Ia[this.i],this.Ia[this.i+1]],null):M(this.v)};f.aa=function(){if(null==this.v){var a=this.Ia,b=this.i+2;return Ve?Ve(a,b,null):Je.call(null,a,b,null)}var a=this.Ia,b=this.i,c=O(this.v);return Ve?Ve(a,b,c):Je.call(null,a,b,c)};f.P=function(){return this};
f.K=function(a,b){return new Ue(b,this.Ia,this.i,this.v,this.m)};f.M=function(a,b){return R(b,this)};Ue.prototype[Ha]=function(){return Q(this)};function Je(){for(var a=[],b=arguments.length,c=0;;)if(c<b)a.push(arguments[c]),c+=1;else break;switch(a.length){case 1:return Ie(arguments[0]);case 3:return Ve(arguments[0],arguments[1],arguments[2]);default:throw Error([B("Invalid arity: "),B(a.length)].join(""));}}function Ie(a){return Ve(a,0,null)}
function Ve(a,b,c){if(null==c)for(c=a.length;;)if(b<c){if(null!=a[b])return new Ue(null,a,b,null,null);var d=a[b+1];if(u(d)&&(d=d.Ya(),u(d)))return new Ue(null,a,b+2,d,null);b+=2}else return null;else return new Ue(null,a,b,c,null)}function We(a,b,c,d,e){this.l=a;this.Ia=b;this.i=c;this.v=d;this.m=e;this.j=32374860;this.u=0}f=We.prototype;f.toString=function(){return Cb(this)};f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.l};
f.F=function(){var a=this.m;return null!=a?a:this.m=a=Wb(this)};f.o=function(a,b){return ic(this,b)};f.T=function(a,b){return Mc(b,this)};f.U=function(a,b,c){return Pc(b,c,this)};f.V=function(){return M(this.v)};f.aa=function(){var a=this.Ia,b=this.i,c=O(this.v);return Xe?Xe(null,a,b,c):Re.call(null,null,a,b,c)};f.P=function(){return this};f.K=function(a,b){return new We(b,this.Ia,this.i,this.v,this.m)};f.M=function(a,b){return R(b,this)};We.prototype[Ha]=function(){return Q(this)};
function Re(){for(var a=[],b=arguments.length,c=0;;)if(c<b)a.push(arguments[c]),c+=1;else break;switch(a.length){case 1:return Qe(arguments[0]);case 4:return Xe(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error([B("Invalid arity: "),B(a.length)].join(""));}}function Qe(a){return Xe(null,a,0,null)}function Xe(a,b,c,d){if(null==d)for(d=b.length;;)if(c<d){var e=b[c];if(u(e)&&(e=e.Ya(),u(e)))return new We(a,b,c+1,e,null);c+=1}else return null;else return new We(a,b,c,d,null)}
function Ye(a,b,c){this.ba=a;this.tb=b;this.nb=c}Ye.prototype.ha=function(){return this.nb&&this.tb.ha()};Ye.prototype.next=function(){if(this.nb)return this.tb.next();this.nb=!0;return this.ba};Ye.prototype.remove=function(){return Error("Unsupported operation")};function Ze(a,b,c,d,e,g){this.l=a;this.h=b;this.root=c;this.ea=d;this.ba=e;this.m=g;this.j=16123663;this.u=8196}f=Ze.prototype;f.toString=function(){return Cb(this)};f.equiv=function(a){return this.o(null,a)};
f.keys=function(){return Q(ue.c?ue.c(this):ue.call(null,this))};f.entries=function(){return qe(J(this))};f.values=function(){return Q(ve.c?ve.c(this):ve.call(null,this))};f.has=function(a){return Qb(this,a,Cc)===Cc?!1:!0};f.get=function(a,b){return this.G(null,a,b)};
f.forEach=function(a){for(var b=J(this),c=null,d=0,e=0;;)if(e<d){var g=c.N(null,e),h=U(g,0),g=U(g,1);a.a?a.a(g,h):a.call(null,g,h);e+=1}else if(b=J(b))zc(b)?(c=xb(b),b=I(b),h=c,d=T(c),c=h):(c=M(b),h=U(c,0),g=U(c,1),a.a?a.a(g,h):a.call(null,g,h),b=O(b),c=null,d=0),e=0;else return null};f.S=function(a,b){return Qa.g(this,b,null)};f.G=function(a,b,c){return null==b?this.ea?this.ba:c:null==this.root?c:this.root.La(0,Lb(b),b,c)};
f.Fa=function(){var a=this.root?Ab(this.root):pd;return this.ea?new Ye(this.ba,a,!1):a};f.H=function(){return this.l};f.X=function(){return this.h};f.F=function(){var a=this.m;return null!=a?a:this.m=a=Yb(this)};f.o=function(a,b){return oe(this,b)};f.Ta=function(){return new $e({},this.root,this.h,this.ea,this.ba)};
f.Ra=function(a,b,c){if(null==b)return this.ea&&c===this.ba?this:new Ze(this.l,this.ea?this.h:this.h+1,this.root,!0,c,null);a=new Ce;b=(null==this.root?Ke:this.root).ja(0,Lb(b),b,c,a);return b===this.root?this:new Ze(this.l,a.pa?this.h+1:this.h,b,this.ea,this.ba,null)};f.P=function(){if(0<this.h){var a=null!=this.root?this.root.Ya():null;return this.ea?R(new X(null,2,5,qd,[null,this.ba],null),a):a}return null};f.K=function(a,b){return new Ze(b,this.h,this.root,this.ea,this.ba,this.m)};
f.M=function(a,b){if(yc(b))return Ra(this,C.a(b,0),C.a(b,1));for(var c=this,d=J(b);;){if(null==d)return c;var e=M(d);if(yc(e))c=Ra(c,C.a(e,0),C.a(e,1)),d=O(d);else throw Error("conj on a map takes map entries or seqables of map entries");}};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.S(null,c);case 3:return this.G(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.a=function(a,c){return this.S(null,c)};a.g=function(a,c,d){return this.G(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ia(b)))};f.c=function(a){return this.S(null,a)};f.a=function(a,b){return this.G(null,a,b)};var qc=new Ze(null,0,null,!1,null,Zb);Ze.prototype[Ha]=function(){return Q(this)};
function $e(a,b,c,d,e){this.A=a;this.root=b;this.count=c;this.ea=d;this.ba=e;this.j=258;this.u=56}function bf(a,b,c){if(a.A){if(null==b)a.ba!==c&&(a.ba=c),a.ea||(a.count+=1,a.ea=!0);else{var d=new Ce;b=(null==a.root?Ke:a.root).ka(a.A,0,Lb(b),b,c,d);b!==a.root&&(a.root=b);d.pa&&(a.count+=1)}return a}throw Error("assoc! after persistent!");}f=$e.prototype;f.X=function(){if(this.A)return this.count;throw Error("count after persistent!");};
f.S=function(a,b){return null==b?this.ea?this.ba:null:null==this.root?null:this.root.La(0,Lb(b),b)};f.G=function(a,b,c){return null==b?this.ea?this.ba:c:null==this.root?c:this.root.La(0,Lb(b),b,c)};
f.bb=function(a,b){var c;a:if(this.A)if(null!=b?b.j&2048||b.yb||(b.j?0:v(Ua,b)):v(Ua,b))c=bf(this,ze.c?ze.c(b):ze.call(null,b),Ae.c?Ae.c(b):Ae.call(null,b));else{c=J(b);for(var d=this;;){var e=M(c);if(u(e))c=O(c),d=bf(d,ze.c?ze.c(e):ze.call(null,e),Ae.c?Ae.c(e):Ae.call(null,e));else{c=d;break a}}}else throw Error("conj! after persistent");return c};f.cb=function(){var a;if(this.A)this.A=null,a=new Ze(null,this.count,this.root,this.ea,this.ba,null);else throw Error("persistent! called twice");return a};
f.Xa=function(a,b,c){return bf(this,b,c)};var Bd=function Bd(){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;return Bd.w(0<b.length?new K(b.slice(0),0):null)};Bd.w=function(a){for(var b=J(a),c=pb(qc);;)if(b){a=O(O(b));var d=M(b),b=lc(b),c=sb(c,d,b),b=a}else return rb(c)};Bd.R=0;Bd.I=function(a){return Bd.w(J(a))};function cf(a,b){this.s=a;this.ga=b;this.j=32374988;this.u=0}f=cf.prototype;f.toString=function(){return Cb(this)};
f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.ga};f.$=function(){var a=(null!=this.s?this.s.j&128||this.s.ab||(this.s.j?0:v(Na,this.s)):v(Na,this.s))?this.s.$(null):O(this.s);return null==a?null:new cf(a,this.ga)};f.F=function(){return Wb(this)};f.o=function(a,b){return ic(this,b)};f.T=function(a,b){return Mc(b,this)};f.U=function(a,b,c){return Pc(b,c,this)};f.V=function(){return this.s.V(null).kb()};
f.aa=function(){var a=(null!=this.s?this.s.j&128||this.s.ab||(this.s.j?0:v(Na,this.s)):v(Na,this.s))?this.s.$(null):O(this.s);return null!=a?new cf(a,this.ga):Tb};f.P=function(){return this};f.K=function(a,b){return new cf(this.s,b)};f.M=function(a,b){return R(b,this)};cf.prototype[Ha]=function(){return Q(this)};function ue(a){return(a=J(a))?new cf(a,null):null}function ze(a){return Va(a)}function df(a,b){this.s=a;this.ga=b;this.j=32374988;this.u=0}f=df.prototype;f.toString=function(){return Cb(this)};
f.equiv=function(a){return this.o(null,a)};f.H=function(){return this.ga};f.$=function(){var a=(null!=this.s?this.s.j&128||this.s.ab||(this.s.j?0:v(Na,this.s)):v(Na,this.s))?this.s.$(null):O(this.s);return null==a?null:new df(a,this.ga)};f.F=function(){return Wb(this)};f.o=function(a,b){return ic(this,b)};f.T=function(a,b){return Mc(b,this)};f.U=function(a,b,c){return Pc(b,c,this)};f.V=function(){return this.s.V(null).lb()};
f.aa=function(){var a=(null!=this.s?this.s.j&128||this.s.ab||(this.s.j?0:v(Na,this.s)):v(Na,this.s))?this.s.$(null):O(this.s);return null!=a?new df(a,this.ga):Tb};f.P=function(){return this};f.K=function(a,b){return new df(this.s,b)};f.M=function(a,b){return R(b,this)};df.prototype[Ha]=function(){return Q(this)};function ve(a){return(a=J(a))?new df(a,null):null}function Ae(a){return Wa(a)}function ef(a){return u(xd(a))?Qc(function(a,c){return S.a(u(a)?a:vd,c)},a):null}
function $c(a){if(null!=a&&(a.u&4096||a.Ab))return a.name;if("string"===typeof a)return a;throw Error([B("Doesn't support name: "),B(a)].join(""));}function ff(a,b,c){this.i=a;this.end=b;this.step=c}ff.prototype.ha=function(){return 0<this.step?this.i<this.end:this.i>this.end};ff.prototype.next=function(){var a=this.i;this.i+=this.step;return a};function gf(a,b,c,d,e){this.l=a;this.start=b;this.end=c;this.step=d;this.m=e;this.j=32375006;this.u=8192}f=gf.prototype;f.toString=function(){return Cb(this)};
f.equiv=function(a){return this.o(null,a)};f.N=function(a,b){if(b<Ka(this))return this.start+b*this.step;if(this.start>this.end&&0===this.step)return this.start;throw Error("Index out of bounds");};f.da=function(a,b,c){return b<Ka(this)?this.start+b*this.step:this.start>this.end&&0===this.step?this.start:c};f.Fa=function(){return new ff(this.start,this.end,this.step)};f.H=function(){return this.l};
f.$=function(){return 0<this.step?this.start+this.step<this.end?new gf(this.l,this.start+this.step,this.end,this.step,null):null:this.start+this.step>this.end?new gf(this.l,this.start+this.step,this.end,this.step,null):null};f.X=function(){return Ea(lb(this))?0:Math.ceil((this.end-this.start)/this.step)};f.F=function(){var a=this.m;return null!=a?a:this.m=a=Wb(this)};f.o=function(a,b){return ic(this,b)};f.T=function(a,b){return $b(this,b)};
f.U=function(a,b,c){for(a=this.start;;)if(0<this.step?a<this.end:a>this.end)c=b.a?b.a(c,a):b.call(null,c,a),a+=this.step;else return c};f.V=function(){return null==lb(this)?null:this.start};f.aa=function(){return null!=lb(this)?new gf(this.l,this.start+this.step,this.end,this.step,null):Tb};f.P=function(){return 0<this.step?this.start<this.end?this:null:this.start>this.end?this:null};f.K=function(a,b){return new gf(b,this.start,this.end,this.step,this.m)};f.M=function(a,b){return R(b,this)};
gf.prototype[Ha]=function(){return Q(this)};function hf(a){if(a instanceof RegExp)return a;var b;var c=/^\(\?([idmsux]*)\)/;if("string"===typeof a)c=c.exec(a),b=null==c?null:1===T(c)?M(c):be(c);else throw new TypeError("re-find must match against a string.");c=U(b,0);b=U(b,1);c=T(c);return new RegExp(a.substring(c),u(b)?b:"")}
function jf(a,b,c,d,e,g,h){var k=ra;ra=null==ra?null:ra-1;try{if(null!=ra&&0>ra)return H(a,"#");H(a,c);if(0===Ca.c(g))J(h)&&H(a,function(){var a=kf.c(g);return u(a)?a:"..."}());else{if(J(h)){var l=M(h);b.g?b.g(l,a,g):b.call(null,l,a,g)}for(var m=O(h),n=Ca.c(g)-1;;)if(!m||null!=n&&0===n){J(m)&&0===n&&(H(a,d),H(a,function(){var a=kf.c(g);return u(a)?a:"..."}()));break}else{H(a,d);var q=M(m);c=a;h=g;b.g?b.g(q,c,h):b.call(null,q,c,h);var r=O(m);c=n-1;m=r;n=c}}return H(a,e)}finally{ra=k}}
function lf(a,b){for(var c=J(b),d=null,e=0,g=0;;)if(g<e){var h=d.N(null,g);H(a,h);g+=1}else if(c=J(c))d=c,zc(d)?(c=xb(d),e=I(d),d=c,h=T(c),c=e,e=h):(h=M(d),H(a,h),c=O(d),d=null,e=0),g=0;else return null}var mf={'"':'\\"',"\\":"\\\\","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t"};function nf(a){return[B('"'),B(a.replace(RegExp('[\\\\"\b\f\n\r\t]',"g"),function(a){return mf[a]})),B('"')].join("")}
function of(a,b){var c=Dc(Sb(a,za));return c?(c=null!=b?b.j&131072||b.zb?!0:!1:!1)?null!=uc(b):c:c}
function pf(a,b,c){if(null==a)return H(b,"nil");if(of(c,a)){H(b,"^");var d=uc(a);Z.g?Z.g(d,b,c):Z.call(null,d,b,c);H(b," ")}if(a.sb)return a.Db(b);if(null!=a&&(a.j&2147483648||a.O))return a.D(null,b,c);if(!0===a||!1===a||"number"===typeof a)return H(b,""+B(a));if(null!=a&&a.constructor===Object)return H(b,"#js "),d=Y.a(function(b){return new X(null,2,5,qd,[Zc.c(b),a[b]],null)},Ac(a)),qf.ca?qf.ca(d,Z,b,c):qf.call(null,d,Z,b,c);if(Da(a))return jf(b,Z,"#js ["," ","]",c,a);if("string"==typeof a)return u(xa.c(c))?
H(b,nf(a)):H(b,a);if("function"==p(a)){var e=a.name;c=u(function(){var a=null==e;return a?a:/^[\s\xa0]*$/.test(e)}())?"Function":e;return lf(b,kc(["#object[",c,' "',""+B(a),'"]'],0))}if(a instanceof Date)return c=function(a,b){for(var c=""+B(a);;)if(T(c)<b)c=[B("0"),B(c)].join("");else return c},lf(b,kc(['#inst "',""+B(a.getUTCFullYear()),"-",c(a.getUTCMonth()+1,2),"-",c(a.getUTCDate(),2),"T",c(a.getUTCHours(),2),":",c(a.getUTCMinutes(),2),":",c(a.getUTCSeconds(),2),".",c(a.getUTCMilliseconds(),3),
"-",'00:00"'],0));if(a instanceof RegExp)return lf(b,kc(['#"',a.source,'"'],0));if(null!=a&&(a.j&2147483648||a.O))return ob(a,b,c);if(u(a.constructor.eb))return lf(b,kc(["#object[",a.constructor.eb.replace(RegExp("/","g"),"."),"]"],0));e=a.constructor.name;c=u(function(){var a=null==e;return a?a:/^[\s\xa0]*$/.test(e)}())?"Object":e;return lf(b,kc(["#object[",c," ",""+B(a),"]"],0))}function Z(a,b,c){var d=rf.c(c);return u(d)?(c=pc.g(c,sf,pf),d.g?d.g(a,b,c):d.call(null,a,b,c)):pf(a,b,c)}
function Gd(){for(var a=[],b=arguments.length,c=0;;)if(c<b)a.push(arguments[c]),c+=1;else break;var d=0<a.length?new K(a.slice(0),0):null,a=ta();if(vc(d))a="";else{b=B;c=new ga;a:{var e=new Bb(c);Z(M(d),e,a);for(var d=J(O(d)),g=null,h=0,k=0;;)if(k<h){var l=g.N(null,k);H(e," ");Z(l,e,a);k+=1}else if(d=J(d))g=d,zc(g)?(d=xb(g),h=I(g),g=d,l=T(d),d=h,h=l):(l=M(g),H(e," "),Z(l,e,a),d=O(g),g=null,h=0),k=0;else break a}a=""+b(c)}return a}
function qf(a,b,c,d){return jf(c,function(a,c,d){var k=Va(a);b.g?b.g(k,c,d):b.call(null,k,c,d);H(c," ");a=Wa(a);return b.g?b.g(a,c,d):b.call(null,a,c,d)},"{",", ","}",d,J(a))}K.prototype.O=!0;K.prototype.D=function(a,b,c){return jf(b,Z,"("," ",")",c,this)};W.prototype.O=!0;W.prototype.D=function(a,b,c){return jf(b,Z,"("," ",")",c,this)};Ue.prototype.O=!0;Ue.prototype.D=function(a,b,c){return jf(b,Z,"("," ",")",c,this)};se.prototype.O=!0;se.prototype.D=function(a,b,c){return jf(b,Z,"("," ",")",c,this)};
de.prototype.O=!0;de.prototype.D=function(a,b,c){return jf(b,Z,"("," ",")",c,this)};Xc.prototype.O=!0;Xc.prototype.D=function(a,b,c){return jf(b,Z,"("," ",")",c,this)};Ze.prototype.O=!0;Ze.prototype.D=function(a,b,c){return qf(this,Z,b,c)};We.prototype.O=!0;We.prototype.D=function(a,b,c){return jf(b,Z,"("," ",")",c,this)};he.prototype.O=!0;he.prototype.D=function(a,b,c){return jf(b,Z,"["," ","]",c,this)};ed.prototype.O=!0;ed.prototype.D=function(a,b,c){return jf(b,Z,"("," ",")",c,this)};
yd.prototype.O=!0;yd.prototype.D=function(a,b,c){H(b,"#object [cljs.core.Atom ");Z(new ua(null,1,[tf,this.state],null),b,c);return H(b,"]")};df.prototype.O=!0;df.prototype.D=function(a,b,c){return jf(b,Z,"("," ",")",c,this)};X.prototype.O=!0;X.prototype.D=function(a,b,c){return jf(b,Z,"["," ","]",c,this)};Vc.prototype.O=!0;Vc.prototype.D=function(a,b){return H(b,"()")};ua.prototype.O=!0;ua.prototype.D=function(a,b,c){return qf(this,Z,b,c)};gf.prototype.O=!0;
gf.prototype.D=function(a,b,c){return jf(b,Z,"("," ",")",c,this)};cf.prototype.O=!0;cf.prototype.D=function(a,b,c){return jf(b,Z,"("," ",")",c,this)};Uc.prototype.O=!0;Uc.prototype.D=function(a,b,c){return jf(b,Z,"("," ",")",c,this)};Pb.prototype.Sa=!0;Pb.prototype.Oa=function(a,b){if(b instanceof Pb)return Ob(this,b);throw Error([B("Cannot compare "),B(this),B(" to "),B(b)].join(""));};V.prototype.Sa=!0;
V.prototype.Oa=function(a,b){if(b instanceof V)return Yc(this,b);throw Error([B("Cannot compare "),B(this),B(" to "),B(b)].join(""));};he.prototype.Sa=!0;he.prototype.Oa=function(a,b){if(yc(b))return Fc(this,b);throw Error([B("Cannot compare "),B(this),B(" to "),B(b)].join(""));};X.prototype.Sa=!0;X.prototype.Oa=function(a,b){if(yc(b))return Fc(this,b);throw Error([B("Cannot compare "),B(this),B(" to "),B(b)].join(""));};var za=new V(null,"meta","meta",1499536964),Aa=new V(null,"dup","dup",556298533),Cd=new V(null,"validator","validator",-1966190681),tf=new V(null,"val","val",128701612),sf=new V(null,"fallback-impl","fallback-impl",-1501286995),wa=new V(null,"flush-on-newline","flush-on-newline",-151457939),Fd=new Pb(null,"n","n",-2092305744,null),xa=new V(null,"readably","readably",1129599760),kf=new V(null,"more-marker","more-marker",-14717935),Ca=new V(null,"print-length","print-length",1931866356),ud=new Pb(null,
"meta8623","meta8623",-357353640,null),td=new Pb(null,"quote","quote",1377916282,null),sd=new V(null,"arglists","arglists",1661989754),rd=new Pb(null,"nil-iter","nil-iter",1101030523,null),rf=new V(null,"alt-impl","alt-impl",670969595),Ed=new Pb(null,"number?","number?",-1747282210,null);function uf(a,b){for(var c=new ga,d=J(b);;)if(null!=d)c.append(""+B(M(d))),d=O(d),null!=d&&c.append(a);else return c.toString()}function vf(a,b){a:for(var c="/(?:)/"===""+B(b)?S.a(be(R("",Y.a(B,J(a)))),""):be((""+B(a)).split(b));;)if(""===(null==c?null:Xa(c)))c=null==c?null:Ya(c);else break a;return c};var wf=function wf(b,c){return 1>b?new X(null,1,5,qd,[be(Dd(c,Hd(!1)))],null):1>c?null:0<b?kd.a(function(){return function e(b){return new W(null,function(){for(;;){var c=J(b);if(c){if(zc(c)){var k=xb(c),l=T(k),m=dd(l);a:for(var n=0;;)if(n<l){var q=C.a(k,n),q=S.a(q,!0);m.add(q);n+=1}else{k=!0;break a}return k?fd(m.B(),e(I(c))):fd(m.B(),null)}m=M(c);return R(S.a(m,!0),e(N(c)))}return null}},null,null)}(wf(b-1,c-1))}(),function(){return function e(b){return new W(null,function(){for(;;){var c=J(b);
if(c){if(zc(c)){var k=xb(c),l=T(k),m=dd(l);a:for(var n=0;;)if(n<l){var q=C.a(k,n),q=S.a(q,!1);m.add(q);n+=1}else{k=!0;break a}return k?fd(m.B(),e(I(c))):fd(m.B(),null)}m=M(c);return R(S.a(m,!1),e(N(c)))}return null}},null,null)}(wf(b,c-1))}()):null};
function xf(a,b){var c=function(){return function e(b){return new W(null,function(){for(;;){var c=J(b);if(c){var k=c;if(zc(k)){var l=xb(k),m=T(l),n=dd(m);return function(){for(var b=0;;)if(b<m){var e=C.a(l,b);hd(n,nd(B,function(){return function(b,c,e,g,h,k,l){return function A(m){return new W(null,function(){return function(){for(;;){var b=J(m);if(b){if(zc(b)){var c=xb(b),e=T(c),g=dd(e);a:for(var h=0;;)if(h<e){var k=C.a(c,h),l=U(k,0),k=U(k,1),l=u(l)?a.substring(k,k+1):[B("[^"),B(Sb(a,k)),B("]")].join("");
g.add(l);h+=1}else{c=!0;break a}return c?fd(g.B(),A(I(b))):fd(g.B(),null)}c=M(b);g=U(c,0);c=U(c,1);return R(u(g)?a.substring(c,c+1):[B("[^"),B(Sb(a,c)),B("]")].join(""),A(N(b)))}return null}}}(b,c,e,g,h,k,l),null,null)}}(b,e,l,m,n,k,c)(Y.g(ce,e,new gf(null,0,Number.MAX_VALUE,1,null)))}()));b+=1}else return!0}()?fd(n.B(),e(I(k))):fd(n.B(),null)}var q=M(k);return R(nd(B,function(){return function(b,c,e){return function z(g){return new W(null,function(){return function(){for(;;){var b=J(g);if(b){if(zc(b)){var c=
xb(b),e=T(c),h=dd(e);a:for(var k=0;;)if(k<e){var l=C.a(c,k),m=U(l,0),l=U(l,1),m=u(m)?a.substring(l,l+1):[B("[^"),B(Sb(a,l)),B("]")].join("");h.add(m);k+=1}else{c=!0;break a}return c?fd(h.B(),z(I(b))):fd(h.B(),null)}c=M(b);h=U(c,0);c=U(c,1);return R(u(h)?a.substring(c,c+1):[B("[^"),B(Sb(a,c)),B("]")].join(""),z(N(b)))}return null}}}(b,c,e),null,null)}}(q,k,c)(Y.g(ce,q,new gf(null,0,Number.MAX_VALUE,1,null)))}()),e(N(k)))}return null}},null,null)}(wf(b,T(a)))}();return hf([B("^("),B(uf("|",c)),B(")$")].join(""))}
function yf(a){return function(a){return function(c){return wd(function(){return function(a){if("string"===typeof c)a=a.exec(c),a=P.a(M(a),c)?1===T(a)?M(a):be(a):null;else throw new TypeError("re-matches must match against a string.");return a}}(a),a)}}(function(){return function c(a){return new W(null,function(){for(;;){var e=J(a);if(e){if(zc(e)){var g=xb(e),h=T(g),k=dd(h);a:for(var l=0;;)if(l<h){var m=C.a(g,l),n=U(m,0),m=U(m,1),n=xf(n,m);k.add(n);l+=1}else{g=!0;break a}return g?fd(k.B(),c(I(e))):
fd(k.B(),null)}g=M(e);k=U(g,0);g=U(g,1);return R(xf(k,g),c(N(e)))}return null}},null,null)}(a)}())}
function zf(a,b){var c=yf(b);return Kc(lc,function(){return function(c){return function g(h){return new W(null,function(c){return function(){for(var d=h;;)if(d=J(d)){if(zc(d)){var m=xb(d),n=T(m),q=dd(n);a:for(var r=0;;)if(r<n){var t=C.a(m,r);u(c.c?c.c(t):c.call(null,t))&&(t=new X(null,2,5,qd,[t,T(Id(yf(ef(kc([new ye([t,0]),b],0))),a))],null),q.add(t));r+=1}else{m=!0;break a}return m?fd(q.B(),g(I(d))):fd(q.B(),null)}q=M(d);if(u(c.c?c.c(q):c.call(null,q)))return R(new X(null,2,5,qd,[q,T(Id(yf(ef(kc([new ye([q,
0]),b],0))),a))],null),g(N(d)));d=N(d)}else return null}}(c),null,null)}}(c)(a)}())}ae("about aware began being bells celts chalk crazy didnt doing dwell earth eight every first games great heard hence heres irish jutes learn local looks meant media meeny mouth never night ninth norse other queer quite risky rural sense shred since speak spoke still stuff their there thing think those today usage welsh whats which women words world would".split(" "));Ad||zd.call(null,mc);
function Af(a){return document.getElementById("msg").innerHTML=a}
function Bf(a){try{var b=a.value,c=function(){return function(a){return function t(b){return new W(null,function(){return function(){for(;;){var a=J(b);if(a){if(zc(a)){var c=xb(a),d=T(c),e=dd(d);a:for(var g=0;;)if(g<d){var h=C.a(c,g),k=e,h=vf(h," ");k.add(h);g+=1}else{c=!0;break a}return c?fd(e.B(),t(I(a))):fd(e.B(),null)}e=M(a);return R(vf(e," "),t(N(a)))}return null}}}(a),null,null)}}(b)(vf(b,"\n"))}(),d=Id(J,Y.a(M,c)),e=Jd(vd,Y.a(function(){return function(a){var b=U(a,0);a=U(a,1);return new X(null,
2,5,qd,[b,parseInt(a)],null)}}(b,c,d),Id(function(){return function(a){return 1<T(a)}}(b,c,d),c))),g=zf(d,e),h=U(g,0),k=U(h,0),l=function(){return function(a){return[B("\x3cstrong\x3e"),B(a),B("\x3c/strong\x3e")].join("")}}(b,c,d,e,g,h,k),m=Id(yf(e),d);return J(m)?Af(nd(B,new X(null,6,5,qd,["You should try ",l(k),".","\x3cbr\x3e","Possible solutions: ",uf(", ",Y.a(l,m))],null))):Af("I have no clue how to solve this.")}catch(n){return Af("errorrrororror")}}
window.onload=function(){var a=document.getElementById("words"),b=function(a){return function(){return Bf(a)}}(a);vc(a.value)&&(a.value=uf("\n",new X(null,12,5,qd,"first;norse;women;their;looks;thing 0;mouth;about 1;eight;media;heres;would".split(";"),null)));setTimeout(b,5);for(var c=J(new X(null,3,5,qd,["onkeyup","onchange","onblur"],null)),d=null,e=0,g=0;;)if(g<e){var h=d.N(null,g);a[h]=b;g+=1}else if(c=J(c))d=c,zc(d)?(c=xb(d),e=I(d),d=c,h=T(c),c=e,e=h):(h=M(d),a[h]=b,c=O(d),d=null,e=0),g=0;else return null};